export class Avalista {
    cep:string;
    cidade:string;
    bairro:string;
    classeSetor:string;
    complemento:string;
    cpf:string;
    dataNascimento:Date;
    estado:string;
    estadoCivil:string;
    idade: number;
    idEstado: string;
    idEstadoCivil:number;
    idNacionalidade:number;
    idOcupacao: number;
    idProfissao:number;
    idSexo:string;
    logradouro:string;
    nacionalidade:string;
    nome:string;
    nomeMae:string;
    nomePai:string;
    numero:string;
    ocupacao:string;
    profissao:string;
    profissaoCargo:string;
    profissaoCidade:string;
    profissaoBairro:string;
    profissaoComplemento:string;
    profissaoDdd:string;
    profissaoEmpresa:string;
    profissaoEstado:string;
    profissaoIdEstado:string;
    profissaoIdCargo:number;
    profissaoLogradouro:string;
    profissaoNumero:string;
    profissaoRamal:string;
    profissaoTelefone:string;
    profissaoCep:string;
    telefoneRamal:string;
    // tempoAnos: number;
    // tempoMeses: number;
    renda:number;
    rendaAdicional:number;
    rendaTotal:number;
    sexo:string;
    idFaixaPatrimonio: number;
    telefoneDdd: string;
    telefoneNumero: string;    
    idUfExpedidor: string;
    celularDdd: string;
    celularNumero: string;   
    cnpjEmpresa: string; 
    // dtAdmissao: Date;
    pessoaPolitica: boolean;
    pessoaRelacaoPolitica: boolean;

    ocupacaoPassivelAlteracao: boolean;
   
    cepAlterado:boolean;
    cidadeAlterado:boolean;
    bairroAlterado:boolean;
    classeSetorAlterado:boolean;
    complementoAlterado:boolean;
    cpfAlterado:boolean;
    dataNascimentoAlterado:boolean;
    telefoneDddAlterado:boolean;
    estadoAlterado:boolean;
    estadoCivilAlterado:boolean;
    idadeAlterado: boolean;
    idEstadoAlterado: boolean;
    idEstadoCivilAlterado:boolean;
    idNacionalidadeAlterado:boolean;
    idOcupacaoAlterado:boolean;
    idProfissaoAlterado:boolean;
    idSexoAlterado:boolean;
    logradouroAlterado:boolean;
    nacionalidadeAlterado:boolean;
    nomeAlterado:boolean;
    nomeMaeAlterado:boolean;
    nomePaiAlterado:boolean;
    numeroAlterado:boolean;
    ocupacaoAlterado:boolean;
    profissaoAlterado:boolean;
    profissaoCargoAlterado:boolean;
    profissaoCidadeAlterado:boolean;
    profissaoBairroAlterado:boolean;
    profissaoComplementoAlterado:boolean;
    profissaoDddAlterado:boolean;
    profissaoEmpresaAlterado:boolean;
    profissaoEstadoAlterado:boolean;
    profissaoIdCargoAlterado:boolean;
    profissaoLogradouroAlterado:boolean;
    profissaoNumeroAlterado:boolean;
    profissaoRamalAlterado:boolean;
    profissaoTelefoneAlterado:boolean;
    profissaoCepAlterado:boolean;
    idFaixaPatrimonioAlterado: boolean;
    telefoneRamalAlterado:boolean;
    // tempoAnosAlterado: boolean;
    // tempoMesesAlterado: boolean;
    rendaAlterado:boolean;
    rendaAdicionalAlterado:boolean;
    rendaTotalAlterado:boolean;
    sexoAlterado:boolean;
    telefoneNumeroAlterado:boolean;
    idUfExpedidorAlterado: boolean;
    celularDddAlterado: boolean;
    celularNumeroAlterado: boolean; 
    cnpjEmpresaAlterado: boolean; 
    // dtAdmissaoAlterado: boolean; 
    pessoaPoliticaAlterado: boolean;
    pessoaRelacaoPoliticaAlterado: boolean;
}