//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaFilaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaGeral", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class FilaGeral : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BloquearAcoesNaDecisaoFixaField;
        
        private bool CapturaField;
        
        private ServicesReference.MesaFilaService.FilasTotais[] FilaTotaisField;
        
        private bool LeituraField;
        
        private int TotalAnaliseField;
        
        private int TotalFilaField;
        
        private int TotalUsuariosAnaliseField;
        
        private int TotalUsuariosFilaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BloquearAcoesNaDecisaoFixa
        {
            get
            {
                return this.BloquearAcoesNaDecisaoFixaField;
            }
            set
            {
                this.BloquearAcoesNaDecisaoFixaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Captura
        {
            get
            {
                return this.CapturaField;
            }
            set
            {
                this.CapturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaFilaService.FilasTotais[] FilaTotais
        {
            get
            {
                return this.FilaTotaisField;
            }
            set
            {
                this.FilaTotaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Leitura
        {
            get
            {
                return this.LeituraField;
            }
            set
            {
                this.LeituraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAnalise
        {
            get
            {
                return this.TotalAnaliseField;
            }
            set
            {
                this.TotalAnaliseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFila
        {
            get
            {
                return this.TotalFilaField;
            }
            set
            {
                this.TotalFilaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalUsuariosAnalise
        {
            get
            {
                return this.TotalUsuariosAnaliseField;
            }
            set
            {
                this.TotalUsuariosAnaliseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalUsuariosFila
        {
            get
            {
                return this.TotalUsuariosFilaField;
            }
            set
            {
                this.TotalUsuariosFilaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilasTotais", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class FilasTotais : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ds_mesaField;
        
        private string id_catalogoField;
        
        private int id_filaField;
        
        private string nm_filaField;
        
        private int qtd_emanaliseField;
        
        private int qtd_filaField;
        
        private int qtd_total_usuariosField;
        
        private int qtd_usuarios_analiseField;
        
        private int qtd_usuarios_filaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_mesa
        {
            get
            {
                return this.ds_mesaField;
            }
            set
            {
                this.ds_mesaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_catalogo
        {
            get
            {
                return this.id_catalogoField;
            }
            set
            {
                this.id_catalogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_fila
        {
            get
            {
                return this.id_filaField;
            }
            set
            {
                this.id_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nm_fila
        {
            get
            {
                return this.nm_filaField;
            }
            set
            {
                this.nm_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qtd_emanalise
        {
            get
            {
                return this.qtd_emanaliseField;
            }
            set
            {
                this.qtd_emanaliseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qtd_fila
        {
            get
            {
                return this.qtd_filaField;
            }
            set
            {
                this.qtd_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qtd_total_usuarios
        {
            get
            {
                return this.qtd_total_usuariosField;
            }
            set
            {
                this.qtd_total_usuariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qtd_usuarios_analise
        {
            get
            {
                return this.qtd_usuarios_analiseField;
            }
            set
            {
                this.qtd_usuarios_analiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qtd_usuarios_fila
        {
            get
            {
                return this.qtd_usuarios_filaField;
            }
            set
            {
                this.qtd_usuarios_filaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioProposta", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class UsuarioProposta : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CorLinhaField;
        
        private string ds_motivoField;
        
        private string ds_produtoField;
        
        private string ds_tipo_motivoField;
        
        private System.DateTime dt_inclusaoField;
        
        private int fl_mensagensField;
        
        private int fl_retornoField;
        
        private string id_catalogoField;
        
        private long id_clienteField;
        
        private int id_filaField;
        
        private string id_pessoaField;
        
        private int id_prioridadeField;
        
        private string id_propostaField;
        
        private int id_servicoField;
        
        private string id_status_analiseField;
        
        private string nm_cliente_rsocField;
        
        private string tp_mesaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorLinha
        {
            get
            {
                return this.CorLinhaField;
            }
            set
            {
                this.CorLinhaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_motivo
        {
            get
            {
                return this.ds_motivoField;
            }
            set
            {
                this.ds_motivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_produto
        {
            get
            {
                return this.ds_produtoField;
            }
            set
            {
                this.ds_produtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_tipo_motivo
        {
            get
            {
                return this.ds_tipo_motivoField;
            }
            set
            {
                this.ds_tipo_motivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt_inclusao
        {
            get
            {
                return this.dt_inclusaoField;
            }
            set
            {
                this.dt_inclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fl_mensagens
        {
            get
            {
                return this.fl_mensagensField;
            }
            set
            {
                this.fl_mensagensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fl_retorno
        {
            get
            {
                return this.fl_retornoField;
            }
            set
            {
                this.fl_retornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_catalogo
        {
            get
            {
                return this.id_catalogoField;
            }
            set
            {
                this.id_catalogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_cliente
        {
            get
            {
                return this.id_clienteField;
            }
            set
            {
                this.id_clienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_fila
        {
            get
            {
                return this.id_filaField;
            }
            set
            {
                this.id_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_pessoa
        {
            get
            {
                return this.id_pessoaField;
            }
            set
            {
                this.id_pessoaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_prioridade
        {
            get
            {
                return this.id_prioridadeField;
            }
            set
            {
                this.id_prioridadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_proposta
        {
            get
            {
                return this.id_propostaField;
            }
            set
            {
                this.id_propostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_servico
        {
            get
            {
                return this.id_servicoField;
            }
            set
            {
                this.id_servicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_status_analise
        {
            get
            {
                return this.id_status_analiseField;
            }
            set
            {
                this.id_status_analiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nm_cliente_rsoc
        {
            get
            {
                return this.nm_cliente_rsocField;
            }
            set
            {
                this.nm_cliente_rsocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tp_mesa
        {
            get
            {
                return this.tp_mesaField;
            }
            set
            {
                this.tp_mesaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioPropostaComite", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class UsuarioPropostaComite : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CorLinhaField;
        
        private string cargo_1Field;
        
        private string cargo_2Field;
        
        private System.DateTime data_1Field;
        
        private System.DateTime data_2Field;
        
        private string ds_motivoField;
        
        private string ds_produtoField;
        
        private string ds_tipo_motivoField;
        
        private System.DateTime dt_inclusaoField;
        
        private string fl_mensagensField;
        
        private string fl_retornoField;
        
        private string id_catalogoField;
        
        private long id_clienteField;
        
        private string id_filaField;
        
        private string id_pessoaField;
        
        private string id_prioridadeField;
        
        private string id_propostaField;
        
        private string id_servicoField;
        
        private string id_status_analiseField;
        
        private string nm_cliente_rsocField;
        
        private string tp_mesaField;
        
        private string usuario_1Field;
        
        private string usuario_2Field;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorLinha
        {
            get
            {
                return this.CorLinhaField;
            }
            set
            {
                this.CorLinhaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cargo_1
        {
            get
            {
                return this.cargo_1Field;
            }
            set
            {
                this.cargo_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cargo_2
        {
            get
            {
                return this.cargo_2Field;
            }
            set
            {
                this.cargo_2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data_1
        {
            get
            {
                return this.data_1Field;
            }
            set
            {
                this.data_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data_2
        {
            get
            {
                return this.data_2Field;
            }
            set
            {
                this.data_2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_motivo
        {
            get
            {
                return this.ds_motivoField;
            }
            set
            {
                this.ds_motivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_produto
        {
            get
            {
                return this.ds_produtoField;
            }
            set
            {
                this.ds_produtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_tipo_motivo
        {
            get
            {
                return this.ds_tipo_motivoField;
            }
            set
            {
                this.ds_tipo_motivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt_inclusao
        {
            get
            {
                return this.dt_inclusaoField;
            }
            set
            {
                this.dt_inclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fl_mensagens
        {
            get
            {
                return this.fl_mensagensField;
            }
            set
            {
                this.fl_mensagensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fl_retorno
        {
            get
            {
                return this.fl_retornoField;
            }
            set
            {
                this.fl_retornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_catalogo
        {
            get
            {
                return this.id_catalogoField;
            }
            set
            {
                this.id_catalogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_cliente
        {
            get
            {
                return this.id_clienteField;
            }
            set
            {
                this.id_clienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_fila
        {
            get
            {
                return this.id_filaField;
            }
            set
            {
                this.id_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_pessoa
        {
            get
            {
                return this.id_pessoaField;
            }
            set
            {
                this.id_pessoaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_prioridade
        {
            get
            {
                return this.id_prioridadeField;
            }
            set
            {
                this.id_prioridadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_proposta
        {
            get
            {
                return this.id_propostaField;
            }
            set
            {
                this.id_propostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_servico
        {
            get
            {
                return this.id_servicoField;
            }
            set
            {
                this.id_servicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_status_analise
        {
            get
            {
                return this.id_status_analiseField;
            }
            set
            {
                this.id_status_analiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nm_cliente_rsoc
        {
            get
            {
                return this.nm_cliente_rsocField;
            }
            set
            {
                this.nm_cliente_rsocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tp_mesa
        {
            get
            {
                return this.tp_mesaField;
            }
            set
            {
                this.tp_mesaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_1
        {
            get
            {
                return this.usuario_1Field;
            }
            set
            {
                this.usuario_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_2
        {
            get
            {
                return this.usuario_2Field;
            }
            set
            {
                this.usuario_2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalheFilaProposta", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class DetalheFilaProposta : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BloquearAcoesNaDecisaoDaFichaField;
        
        private ServicesReference.MesaFilaService.FilaDetalhe[] ListaDetalheField;
        
        private bool SelecionarPropostaParaAnaliseField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BloquearAcoesNaDecisaoDaFicha
        {
            get
            {
                return this.BloquearAcoesNaDecisaoDaFichaField;
            }
            set
            {
                this.BloquearAcoesNaDecisaoDaFichaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaFilaService.FilaDetalhe[] ListaDetalhe
        {
            get
            {
                return this.ListaDetalheField;
            }
            set
            {
                this.ListaDetalheField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SelecionarPropostaParaAnalise
        {
            get
            {
                return this.SelecionarPropostaParaAnaliseField;
            }
            set
            {
                this.SelecionarPropostaParaAnaliseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaDetalhe", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class FilaDetalhe : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ds_alcadaField;
        
        private string ds_catalogoField;
        
        private string ds_mesaField;
        
        private string ds_produtoField;
        
        private System.DateTime dt_inclusaoField;
        
        private System.Nullable<System.DateTime> dt_inicio_analiseField;
        
        private string fl_fax_recebidoField;
        
        private int fl_mensagensField;
        
        private int id_alcadaField;
        
        private long id_clienteField;
        
        private int id_filaField;
        
        private string id_pessoaField;
        
        private int id_prioridadeField;
        
        private int id_produtoField;
        
        private string id_propostaField;
        
        private long id_proposta_numericoField;
        
        private int id_servicoField;
        
        private string id_status_analiseField;
        
        private string id_usuarioField;
        
        private string id_usucodigoField;
        
        private string nm_cliente_razao_socialField;
        
        private string nm_filaField;
        
        private string tp_analiseField;
        
        private string tp_filaField;
        
        private string tp_mesaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_alcada
        {
            get
            {
                return this.ds_alcadaField;
            }
            set
            {
                this.ds_alcadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_catalogo
        {
            get
            {
                return this.ds_catalogoField;
            }
            set
            {
                this.ds_catalogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_mesa
        {
            get
            {
                return this.ds_mesaField;
            }
            set
            {
                this.ds_mesaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_produto
        {
            get
            {
                return this.ds_produtoField;
            }
            set
            {
                this.ds_produtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt_inclusao
        {
            get
            {
                return this.dt_inclusaoField;
            }
            set
            {
                this.dt_inclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dt_inicio_analise
        {
            get
            {
                return this.dt_inicio_analiseField;
            }
            set
            {
                this.dt_inicio_analiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fl_fax_recebido
        {
            get
            {
                return this.fl_fax_recebidoField;
            }
            set
            {
                this.fl_fax_recebidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fl_mensagens
        {
            get
            {
                return this.fl_mensagensField;
            }
            set
            {
                this.fl_mensagensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_alcada
        {
            get
            {
                return this.id_alcadaField;
            }
            set
            {
                this.id_alcadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_cliente
        {
            get
            {
                return this.id_clienteField;
            }
            set
            {
                this.id_clienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_fila
        {
            get
            {
                return this.id_filaField;
            }
            set
            {
                this.id_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_pessoa
        {
            get
            {
                return this.id_pessoaField;
            }
            set
            {
                this.id_pessoaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_prioridade
        {
            get
            {
                return this.id_prioridadeField;
            }
            set
            {
                this.id_prioridadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_produto
        {
            get
            {
                return this.id_produtoField;
            }
            set
            {
                this.id_produtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_proposta
        {
            get
            {
                return this.id_propostaField;
            }
            set
            {
                this.id_propostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_proposta_numerico
        {
            get
            {
                return this.id_proposta_numericoField;
            }
            set
            {
                this.id_proposta_numericoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_servico
        {
            get
            {
                return this.id_servicoField;
            }
            set
            {
                this.id_servicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_status_analise
        {
            get
            {
                return this.id_status_analiseField;
            }
            set
            {
                this.id_status_analiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_usuario
        {
            get
            {
                return this.id_usuarioField;
            }
            set
            {
                this.id_usuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_usucodigo
        {
            get
            {
                return this.id_usucodigoField;
            }
            set
            {
                this.id_usucodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nm_cliente_razao_social
        {
            get
            {
                return this.nm_cliente_razao_socialField;
            }
            set
            {
                this.nm_cliente_razao_socialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nm_fila
        {
            get
            {
                return this.nm_filaField;
            }
            set
            {
                this.nm_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tp_analise
        {
            get
            {
                return this.tp_analiseField;
            }
            set
            {
                this.tp_analiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tp_fila
        {
            get
            {
                return this.tp_filaField;
            }
            set
            {
                this.tp_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tp_mesa
        {
            get
            {
                return this.tp_mesaField;
            }
            set
            {
                this.tp_mesaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropostaAcompanhamento", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class PropostaAcompanhamento : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DtEntradaField;
        
        private System.Nullable<System.DateTime> DtSaidaField;
        
        private string MotivoField;
        
        private string TempoField;
        
        private string UsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtEntrada
        {
            get
            {
                return this.DtEntradaField;
            }
            set
            {
                this.DtEntradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DtSaida
        {
            get
            {
                return this.DtSaidaField;
            }
            set
            {
                this.DtSaidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo
        {
            get
            {
                return this.MotivoField;
            }
            set
            {
                this.MotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tempo
        {
            get
            {
                return this.TempoField;
            }
            set
            {
                this.TempoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropostaDecidida", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Fila")]
    public partial class PropostaDecidida : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ServicesReference.MesaFilaService.FilaPropostaDecidida[] FilaPropostaDecididaField;
        
        private int TotaisField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaFilaService.FilaPropostaDecidida[] FilaPropostaDecidida
        {
            get
            {
                return this.FilaPropostaDecididaField;
            }
            set
            {
                this.FilaPropostaDecididaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Totais
        {
            get
            {
                return this.TotaisField;
            }
            set
            {
                this.TotaisField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaPropostaDecidida", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Fila")]
    public partial class FilaPropostaDecidida : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsPropostaDecisaoField;
        
        private int IdPropostaDecisaoField;
        
        private int QtdeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsPropostaDecisao
        {
            get
            {
                return this.DsPropostaDecisaoField;
            }
            set
            {
                this.DsPropostaDecisaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPropostaDecisao
        {
            get
            {
                return this.IdPropostaDecisaoField;
            }
            set
            {
                this.IdPropostaDecisaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qtde
        {
            get
            {
                return this.QtdeField;
            }
            set
            {
                this.QtdeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalhePropostaDecidida", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Fila")]
    public partial class DetalhePropostaDecidida : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cd_conceitoField;
        
        private string ds_alcadaField;
        
        private string ds_catalogoField;
        
        private string ds_mesaField;
        
        private string ds_produtoField;
        
        private string ds_proposta_statusField;
        
        private System.DateTime dt_decisaoField;
        
        private System.DateTime dt_inclusaoField;
        
        private System.Nullable<System.DateTime> dt_inicio_analiseField;
        
        private string fl_cancelada_aprovadaField;
        
        private string fl_consulta_scrField;
        
        private string fl_fax_recebidoField;
        
        private int fl_mensagensField;
        
        private int id_alcadaField;
        
        private long id_clienteField;
        
        private int id_filaField;
        
        private int id_operadorField;
        
        private string id_pessoaField;
        
        private int id_prioridadeField;
        
        private int id_produtoField;
        
        private string id_propostaField;
        
        private long id_proposta_numericoField;
        
        private int id_servicoField;
        
        private int id_situacaoField;
        
        private string id_status_analiseField;
        
        private string id_usuarioField;
        
        private string id_usucodigoField;
        
        private string nm_cliente_razao_socialField;
        
        private string nm_filaField;
        
        private string operadorField;
        
        private string tempo_respostaField;
        
        private string tipo_proposta_maeField;
        
        private string tp_analiseField;
        
        private string tp_filaField;
        
        private string tp_mesaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cd_conceito
        {
            get
            {
                return this.cd_conceitoField;
            }
            set
            {
                this.cd_conceitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_alcada
        {
            get
            {
                return this.ds_alcadaField;
            }
            set
            {
                this.ds_alcadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_catalogo
        {
            get
            {
                return this.ds_catalogoField;
            }
            set
            {
                this.ds_catalogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_mesa
        {
            get
            {
                return this.ds_mesaField;
            }
            set
            {
                this.ds_mesaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_produto
        {
            get
            {
                return this.ds_produtoField;
            }
            set
            {
                this.ds_produtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_proposta_status
        {
            get
            {
                return this.ds_proposta_statusField;
            }
            set
            {
                this.ds_proposta_statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt_decisao
        {
            get
            {
                return this.dt_decisaoField;
            }
            set
            {
                this.dt_decisaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt_inclusao
        {
            get
            {
                return this.dt_inclusaoField;
            }
            set
            {
                this.dt_inclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dt_inicio_analise
        {
            get
            {
                return this.dt_inicio_analiseField;
            }
            set
            {
                this.dt_inicio_analiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fl_cancelada_aprovada
        {
            get
            {
                return this.fl_cancelada_aprovadaField;
            }
            set
            {
                this.fl_cancelada_aprovadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fl_consulta_scr
        {
            get
            {
                return this.fl_consulta_scrField;
            }
            set
            {
                this.fl_consulta_scrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fl_fax_recebido
        {
            get
            {
                return this.fl_fax_recebidoField;
            }
            set
            {
                this.fl_fax_recebidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fl_mensagens
        {
            get
            {
                return this.fl_mensagensField;
            }
            set
            {
                this.fl_mensagensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_alcada
        {
            get
            {
                return this.id_alcadaField;
            }
            set
            {
                this.id_alcadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_cliente
        {
            get
            {
                return this.id_clienteField;
            }
            set
            {
                this.id_clienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_fila
        {
            get
            {
                return this.id_filaField;
            }
            set
            {
                this.id_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_operador
        {
            get
            {
                return this.id_operadorField;
            }
            set
            {
                this.id_operadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_pessoa
        {
            get
            {
                return this.id_pessoaField;
            }
            set
            {
                this.id_pessoaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_prioridade
        {
            get
            {
                return this.id_prioridadeField;
            }
            set
            {
                this.id_prioridadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_produto
        {
            get
            {
                return this.id_produtoField;
            }
            set
            {
                this.id_produtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_proposta
        {
            get
            {
                return this.id_propostaField;
            }
            set
            {
                this.id_propostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_proposta_numerico
        {
            get
            {
                return this.id_proposta_numericoField;
            }
            set
            {
                this.id_proposta_numericoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_servico
        {
            get
            {
                return this.id_servicoField;
            }
            set
            {
                this.id_servicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_situacao
        {
            get
            {
                return this.id_situacaoField;
            }
            set
            {
                this.id_situacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_status_analise
        {
            get
            {
                return this.id_status_analiseField;
            }
            set
            {
                this.id_status_analiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_usuario
        {
            get
            {
                return this.id_usuarioField;
            }
            set
            {
                this.id_usuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_usucodigo
        {
            get
            {
                return this.id_usucodigoField;
            }
            set
            {
                this.id_usucodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nm_cliente_razao_social
        {
            get
            {
                return this.nm_cliente_razao_socialField;
            }
            set
            {
                this.nm_cliente_razao_socialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nm_fila
        {
            get
            {
                return this.nm_filaField;
            }
            set
            {
                this.nm_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operador
        {
            get
            {
                return this.operadorField;
            }
            set
            {
                this.operadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tempo_resposta
        {
            get
            {
                return this.tempo_respostaField;
            }
            set
            {
                this.tempo_respostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_proposta_mae
        {
            get
            {
                return this.tipo_proposta_maeField;
            }
            set
            {
                this.tipo_proposta_maeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tp_analise
        {
            get
            {
                return this.tp_analiseField;
            }
            set
            {
                this.tp_analiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tp_fila
        {
            get
            {
                return this.tp_filaField;
            }
            set
            {
                this.tp_filaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tp_mesa
        {
            get
            {
                return this.tp_mesaField;
            }
            set
            {
                this.tp_mesaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaFilaService.IMesaFilasService")]
    public interface IMesaFilasService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/ObterFilaGeral", ReplyAction="http://tempuri.org/IMesaFilasService/ObterFilaGeralResponse")]
        ServicesReference.MesaFilaService.FilaGeral ObterFilaGeral(string idUsoCodigo, string tipoLista, string idCatalogo, string idCliente, string proposta, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/ObterFilaGeral", ReplyAction="http://tempuri.org/IMesaFilasService/ObterFilaGeralResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaFilaService.FilaGeral> ObterFilaGeralAsync(string idUsoCodigo, string tipoLista, string idCatalogo, string idCliente, string proposta, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/ObterFilaPessoal", ReplyAction="http://tempuri.org/IMesaFilasService/ObterFilaPessoalResponse")]
        ServicesReference.MesaFilaService.UsuarioProposta[] ObterFilaPessoal(string idusuariocod, string idcatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/ObterFilaPessoal", ReplyAction="http://tempuri.org/IMesaFilasService/ObterFilaPessoalResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaFilaService.UsuarioProposta[]> ObterFilaPessoalAsync(string idusuariocod, string idcatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/ObterFilaComite", ReplyAction="http://tempuri.org/IMesaFilasService/ObterFilaComiteResponse")]
        ServicesReference.MesaFilaService.UsuarioPropostaComite[] ObterFilaComite(string idusuariocod, string idcatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/ObterFilaComite", ReplyAction="http://tempuri.org/IMesaFilasService/ObterFilaComiteResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaFilaService.UsuarioPropostaComite[]> ObterFilaComiteAsync(string idusuariocod, string idcatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/DetalheFilaGeral", ReplyAction="http://tempuri.org/IMesaFilasService/DetalheFilaGeralResponse")]
        ServicesReference.MesaFilaService.DetalheFilaProposta DetalheFilaGeral(int idfila, string idUsuario, bool captura, string idcliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/DetalheFilaGeral", ReplyAction="http://tempuri.org/IMesaFilasService/DetalheFilaGeralResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaFilaService.DetalheFilaProposta> DetalheFilaGeralAsync(int idfila, string idUsuario, bool captura, string idcliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/ListarAcompanhamentos", ReplyAction="http://tempuri.org/IMesaFilasService/ListarAcompanhamentosResponse")]
        ServicesReference.MesaFilaService.PropostaAcompanhamento[] ListarAcompanhamentos(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/ListarAcompanhamentos", ReplyAction="http://tempuri.org/IMesaFilasService/ListarAcompanhamentosResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaFilaService.PropostaAcompanhamento[]> ListarAcompanhamentosAsync(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/ObterFilaDecidida", ReplyAction="http://tempuri.org/IMesaFilasService/ObterFilaDecididaResponse")]
        ServicesReference.MesaFilaService.PropostaDecidida ObterFilaDecidida(string idCliente, string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/ObterFilaDecidida", ReplyAction="http://tempuri.org/IMesaFilasService/ObterFilaDecididaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaFilaService.PropostaDecidida> ObterFilaDecididaAsync(string idCliente, string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/DetalheFilaDecidida", ReplyAction="http://tempuri.org/IMesaFilasService/DetalheFilaDecididaResponse")]
        ServicesReference.MesaFilaService.DetalhePropostaDecidida[] DetalheFilaDecidida(int idDecisao, int idFila, string idProposta, string idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaFilasService/DetalheFilaDecidida", ReplyAction="http://tempuri.org/IMesaFilasService/DetalheFilaDecididaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaFilaService.DetalhePropostaDecidida[]> DetalheFilaDecididaAsync(int idDecisao, int idFila, string idProposta, string idCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaFilasServiceChannel : ServicesReference.MesaFilaService.IMesaFilasService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaFilasServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaFilaService.IMesaFilasService>, ServicesReference.MesaFilaService.IMesaFilasService
    {
        
        public MesaFilasServiceClient()
        {
        }
        
        public MesaFilasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaFilasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaFilasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaFilasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaFilaService.FilaGeral ObterFilaGeral(string idUsoCodigo, string tipoLista, string idCatalogo, string idCliente, string proposta, string nome)
        {
            return base.Channel.ObterFilaGeral(idUsoCodigo, tipoLista, idCatalogo, idCliente, proposta, nome);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaFilaService.FilaGeral> ObterFilaGeralAsync(string idUsoCodigo, string tipoLista, string idCatalogo, string idCliente, string proposta, string nome)
        {
            return base.Channel.ObterFilaGeralAsync(idUsoCodigo, tipoLista, idCatalogo, idCliente, proposta, nome);
        }
        
        public ServicesReference.MesaFilaService.UsuarioProposta[] ObterFilaPessoal(string idusuariocod, string idcatalogo)
        {
            return base.Channel.ObterFilaPessoal(idusuariocod, idcatalogo);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaFilaService.UsuarioProposta[]> ObterFilaPessoalAsync(string idusuariocod, string idcatalogo)
        {
            return base.Channel.ObterFilaPessoalAsync(idusuariocod, idcatalogo);
        }
        
        public ServicesReference.MesaFilaService.UsuarioPropostaComite[] ObterFilaComite(string idusuariocod, string idcatalogo)
        {
            return base.Channel.ObterFilaComite(idusuariocod, idcatalogo);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaFilaService.UsuarioPropostaComite[]> ObterFilaComiteAsync(string idusuariocod, string idcatalogo)
        {
            return base.Channel.ObterFilaComiteAsync(idusuariocod, idcatalogo);
        }
        
        public ServicesReference.MesaFilaService.DetalheFilaProposta DetalheFilaGeral(int idfila, string idUsuario, bool captura, string idcliente)
        {
            return base.Channel.DetalheFilaGeral(idfila, idUsuario, captura, idcliente);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaFilaService.DetalheFilaProposta> DetalheFilaGeralAsync(int idfila, string idUsuario, bool captura, string idcliente)
        {
            return base.Channel.DetalheFilaGeralAsync(idfila, idUsuario, captura, idcliente);
        }
        
        public ServicesReference.MesaFilaService.PropostaAcompanhamento[] ListarAcompanhamentos(string idProposta)
        {
            return base.Channel.ListarAcompanhamentos(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaFilaService.PropostaAcompanhamento[]> ListarAcompanhamentosAsync(string idProposta)
        {
            return base.Channel.ListarAcompanhamentosAsync(idProposta);
        }
        
        public ServicesReference.MesaFilaService.PropostaDecidida ObterFilaDecidida(string idCliente, string idProposta)
        {
            return base.Channel.ObterFilaDecidida(idCliente, idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaFilaService.PropostaDecidida> ObterFilaDecididaAsync(string idCliente, string idProposta)
        {
            return base.Channel.ObterFilaDecididaAsync(idCliente, idProposta);
        }
        
        public ServicesReference.MesaFilaService.DetalhePropostaDecidida[] DetalheFilaDecidida(int idDecisao, int idFila, string idProposta, string idCliente)
        {
            return base.Channel.DetalheFilaDecidida(idDecisao, idFila, idProposta, idCliente);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaFilaService.DetalhePropostaDecidida[]> DetalheFilaDecididaAsync(int idDecisao, int idFila, string idProposta, string idCliente)
        {
            return base.Channel.DetalheFilaDecididaAsync(idDecisao, idFila, idProposta, idCliente);
        }
    }
}
