//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaConsultasExternasBureauProfissaoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BureauProfissao", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Bureaus.Profissao")]
    public partial class BureauProfissao : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ServicesReference.MesaConsultasExternasBureauProfissaoService.BureauCargo[] CargosField;
        
        private ServicesReference.MesaConsultasExternasBureauProfissaoService.BureauEscolaridade[] EscolaridadesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasBureauProfissaoService.BureauCargo[] Cargos
        {
            get
            {
                return this.CargosField;
            }
            set
            {
                this.CargosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasBureauProfissaoService.BureauEscolaridade[] Escolaridades
        {
            get
            {
                return this.EscolaridadesField;
            }
            set
            {
                this.EscolaridadesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BureauCargo", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Bureaus.Profissao")]
    public partial class BureauCargo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CargoField;
        
        private string OrigemField;
        
        private string ProfissaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo
        {
            get
            {
                return this.CargoField;
            }
            set
            {
                this.CargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origem
        {
            get
            {
                return this.OrigemField;
            }
            set
            {
                this.OrigemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profissao
        {
            get
            {
                return this.ProfissaoField;
            }
            set
            {
                this.ProfissaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BureauEscolaridade", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Bureaus.Profissao")]
    public partial class BureauEscolaridade : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EscolaridadeField;
        
        private string OrigemField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Escolaridade
        {
            get
            {
                return this.EscolaridadeField;
            }
            set
            {
                this.EscolaridadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origem
        {
            get
            {
                return this.OrigemField;
            }
            set
            {
                this.OrigemField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaConsultasExternasBureauProfissaoService.IMesaConsultasExter" +
        "nasBureauProfissaoService")]
    public interface IMesaConsultasExternasBureauProfissaoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasBureauProfissaoService/GetBureauProfissa" +
            "o", ReplyAction="http://tempuri.org/IMesaConsultasExternasBureauProfissaoService/GetBureauProfissa" +
            "oResponse")]
        ServicesReference.MesaConsultasExternasBureauProfissaoService.BureauProfissao GetBureauProfissao(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasBureauProfissaoService/GetBureauProfissa" +
            "o", ReplyAction="http://tempuri.org/IMesaConsultasExternasBureauProfissaoService/GetBureauProfissa" +
            "oResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasBureauProfissaoService.BureauProfissao> GetBureauProfissaoAsync(string idProposta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaConsultasExternasBureauProfissaoServiceChannel : ServicesReference.MesaConsultasExternasBureauProfissaoService.IMesaConsultasExternasBureauProfissaoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaConsultasExternasBureauProfissaoServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaConsultasExternasBureauProfissaoService.IMesaConsultasExternasBureauProfissaoService>, ServicesReference.MesaConsultasExternasBureauProfissaoService.IMesaConsultasExternasBureauProfissaoService
    {
        
        public MesaConsultasExternasBureauProfissaoServiceClient()
        {
        }
        
        public MesaConsultasExternasBureauProfissaoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaConsultasExternasBureauProfissaoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasBureauProfissaoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasBureauProfissaoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaConsultasExternasBureauProfissaoService.BureauProfissao GetBureauProfissao(string idProposta)
        {
            return base.Channel.GetBureauProfissao(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasBureauProfissaoService.BureauProfissao> GetBureauProfissaoAsync(string idProposta)
        {
            return base.Channel.GetBureauProfissaoAsync(idProposta);
        }
    }
}
