//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaConsultasExternasReceitaFederalService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPessoaEnum", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum TipoPessoaEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisaoGeral = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Proponente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avalista = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conjuge = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cnpj = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceitaFederal", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.ReceitaFederal")]
    public partial class ReceitaFederal : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ServicesReference.MesaConsultasExternasReceitaFederalService.Credd[] CreddField;
        
        private ServicesReference.MesaConsultasExternasReceitaFederalService.Irpf[] IrpfField;
        
        private ServicesReference.MesaConsultasExternasReceitaFederalService.Receita[] ReceitaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasReceitaFederalService.Credd[] Credd
        {
            get
            {
                return this.CreddField;
            }
            set
            {
                this.CreddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasReceitaFederalService.Irpf[] Irpf
        {
            get
            {
                return this.IrpfField;
            }
            set
            {
                this.IrpfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasReceitaFederalService.Receita[] Receita
        {
            get
            {
                return this.ReceitaField;
            }
            set
            {
                this.ReceitaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credd", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.ReceitaFederal")]
    public partial class Credd : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DtConsultaField;
        
        private string NomeReceitaField;
        
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtConsulta
        {
            get
            {
                return this.DtConsultaField;
            }
            set
            {
                this.DtConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeReceita
        {
            get
            {
                return this.NomeReceitaField;
            }
            set
            {
                this.NomeReceitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Irpf", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.ReceitaFederal")]
    public partial class Irpf : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AgenciaField;
        
        private int AnoReferenciaField;
        
        private string BancoField;
        
        private System.DateTime DtDisponibilidadeField;
        
        private string LoteField;
        
        private string SituacaoResgateRestituicaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Agencia
        {
            get
            {
                return this.AgenciaField;
            }
            set
            {
                this.AgenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnoReferencia
        {
            get
            {
                return this.AnoReferenciaField;
            }
            set
            {
                this.AnoReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Banco
        {
            get
            {
                return this.BancoField;
            }
            set
            {
                this.BancoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtDisponibilidade
        {
            get
            {
                return this.DtDisponibilidadeField;
            }
            set
            {
                this.DtDisponibilidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lote
        {
            get
            {
                return this.LoteField;
            }
            set
            {
                this.LoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SituacaoResgateRestituicao
        {
            get
            {
                return this.SituacaoResgateRestituicaoField;
            }
            set
            {
                this.SituacaoResgateRestituicaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Receita", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.ReceitaFederal")]
    public partial class Receita : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CpfField;
        
        private System.DateTime DtInscricaoField;
        
        private string NomeField;
        
        private string SituacaoCadastralField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf
        {
            get
            {
                return this.CpfField;
            }
            set
            {
                this.CpfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtInscricao
        {
            get
            {
                return this.DtInscricaoField;
            }
            set
            {
                this.DtInscricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SituacaoCadastral
        {
            get
            {
                return this.SituacaoCadastralField;
            }
            set
            {
                this.SituacaoCadastralField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaConsultasExternasReceitaFederalService.IMesaConsultasExtern" +
        "asReceitaFederalService")]
    public interface IMesaConsultasExternasReceitaFederalService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasReceitaFederalService/GetReceitaFederal", ReplyAction="http://tempuri.org/IMesaConsultasExternasReceitaFederalService/GetReceitaFederalR" +
            "esponse")]
        ServicesReference.MesaConsultasExternasReceitaFederalService.ReceitaFederal GetReceitaFederal(string idProposta, ServicesReference.MesaConsultasExternasReceitaFederalService.TipoPessoaEnum tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasReceitaFederalService/GetReceitaFederal", ReplyAction="http://tempuri.org/IMesaConsultasExternasReceitaFederalService/GetReceitaFederalR" +
            "esponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasReceitaFederalService.ReceitaFederal> GetReceitaFederalAsync(string idProposta, ServicesReference.MesaConsultasExternasReceitaFederalService.TipoPessoaEnum tipoPessoa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaConsultasExternasReceitaFederalServiceChannel : ServicesReference.MesaConsultasExternasReceitaFederalService.IMesaConsultasExternasReceitaFederalService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaConsultasExternasReceitaFederalServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaConsultasExternasReceitaFederalService.IMesaConsultasExternasReceitaFederalService>, ServicesReference.MesaConsultasExternasReceitaFederalService.IMesaConsultasExternasReceitaFederalService
    {
        
        public MesaConsultasExternasReceitaFederalServiceClient()
        {
        }
        
        public MesaConsultasExternasReceitaFederalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaConsultasExternasReceitaFederalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasReceitaFederalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasReceitaFederalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaConsultasExternasReceitaFederalService.ReceitaFederal GetReceitaFederal(string idProposta, ServicesReference.MesaConsultasExternasReceitaFederalService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetReceitaFederal(idProposta, tipoPessoa);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasReceitaFederalService.ReceitaFederal> GetReceitaFederalAsync(string idProposta, ServicesReference.MesaConsultasExternasReceitaFederalService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetReceitaFederalAsync(idProposta, tipoPessoa);
        }
    }
}
