//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaUtilService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Endereco", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class Endereco : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BairroField;
        
        private string CepField;
        
        private string CidadeField;
        
        private string IdEstadoField;
        
        private string LogradouroField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro
        {
            get
            {
                return this.BairroField;
            }
            set
            {
                this.BairroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep
        {
            get
            {
                return this.CepField;
            }
            set
            {
                this.CepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade
        {
            get
            {
                return this.CidadeField;
            }
            set
            {
                this.CidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro
        {
            get
            {
                return this.LogradouroField;
            }
            set
            {
                this.LogradouroField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametro", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum Parametro : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HoraMesa = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HoraMesaVira = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Renda = 200,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametro", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class Parametro1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdParametroField;
        
        private string MaximoField;
        
        private string MinimoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdParametro
        {
            get
            {
                return this.IdParametroField;
            }
            set
            {
                this.IdParametroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maximo
        {
            get
            {
                return this.MaximoField;
            }
            set
            {
                this.MaximoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Minimo
        {
            get
            {
                return this.MinimoField;
            }
            set
            {
                this.MinimoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoRenda", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum TipoRenda : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mensal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Adicional = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Renda", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum Renda : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaoFoiPossivelValidarRenda = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RendaValida = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RendaAbaixoValorMinimo = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RendaAcimaValorMaximo = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaUtilService.IMesaUtilService")]
    public interface IMesaUtilService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/CalcularIdade", ReplyAction="http://tempuri.org/IMesaUtilService/CalcularIdadeResponse")]
        int CalcularIdade(System.DateTime dataNascimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/CalcularIdade", ReplyAction="http://tempuri.org/IMesaUtilService/CalcularIdadeResponse")]
        System.Threading.Tasks.Task<int> CalcularIdadeAsync(System.DateTime dataNascimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/CalcularTempoServico", ReplyAction="http://tempuri.org/IMesaUtilService/CalcularTempoServicoResponse")]
        System.Collections.Generic.Dictionary<int, int> CalcularTempoServico(System.DateTime dataAdmissao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/CalcularTempoServico", ReplyAction="http://tempuri.org/IMesaUtilService/CalcularTempoServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, int>> CalcularTempoServicoAsync(System.DateTime dataAdmissao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ValidarCep", ReplyAction="http://tempuri.org/IMesaUtilService/ValidarCepResponse")]
        bool ValidarCep(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ValidarCep", ReplyAction="http://tempuri.org/IMesaUtilService/ValidarCepResponse")]
        System.Threading.Tasks.Task<bool> ValidarCepAsync(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ObterEndereco", ReplyAction="http://tempuri.org/IMesaUtilService/ObterEnderecoResponse")]
        ServicesReference.MesaUtilService.Endereco ObterEndereco(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ObterEndereco", ReplyAction="http://tempuri.org/IMesaUtilService/ObterEnderecoResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaUtilService.Endereco> ObterEnderecoAsync(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ValidarCpf", ReplyAction="http://tempuri.org/IMesaUtilService/ValidarCpfResponse")]
        bool ValidarCpf(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ValidarCpf", ReplyAction="http://tempuri.org/IMesaUtilService/ValidarCpfResponse")]
        System.Threading.Tasks.Task<bool> ValidarCpfAsync(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ValidarCnpj", ReplyAction="http://tempuri.org/IMesaUtilService/ValidarCnpjResponse")]
        bool ValidarCnpj(string cnpj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ValidarCnpj", ReplyAction="http://tempuri.org/IMesaUtilService/ValidarCnpjResponse")]
        System.Threading.Tasks.Task<bool> ValidarCnpjAsync(string cnpj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ObterParametro", ReplyAction="http://tempuri.org/IMesaUtilService/ObterParametroResponse")]
        ServicesReference.MesaUtilService.Parametro1 ObterParametro(ServicesReference.MesaUtilService.Parametro idParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ObterParametro", ReplyAction="http://tempuri.org/IMesaUtilService/ObterParametroResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaUtilService.Parametro1> ObterParametroAsync(ServicesReference.MesaUtilService.Parametro idParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ValidarRenda", ReplyAction="http://tempuri.org/IMesaUtilService/ValidarRendaResponse")]
        ServicesReference.MesaUtilService.Renda ValidarRenda(decimal renda, bool rendaObrigatorio, ServicesReference.MesaUtilService.TipoRenda tipoRenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ValidarRenda", ReplyAction="http://tempuri.org/IMesaUtilService/ValidarRendaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaUtilService.Renda> ValidarRendaAsync(decimal renda, bool rendaObrigatorio, ServicesReference.MesaUtilService.TipoRenda tipoRenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ObterHorasMesa", ReplyAction="http://tempuri.org/IMesaUtilService/ObterHorasMesaResponse")]
        int[] ObterHorasMesa(string agendamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ObterHorasMesa", ReplyAction="http://tempuri.org/IMesaUtilService/ObterHorasMesaResponse")]
        System.Threading.Tasks.Task<int[]> ObterHorasMesaAsync(string agendamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ObterHoraAgendamento", ReplyAction="http://tempuri.org/IMesaUtilService/ObterHoraAgendamentoResponse")]
        System.DateTime ObterHoraAgendamento(int tempo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaUtilService/ObterHoraAgendamento", ReplyAction="http://tempuri.org/IMesaUtilService/ObterHoraAgendamentoResponse")]
        System.Threading.Tasks.Task<System.DateTime> ObterHoraAgendamentoAsync(int tempo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaUtilServiceChannel : ServicesReference.MesaUtilService.IMesaUtilService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaUtilServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaUtilService.IMesaUtilService>, ServicesReference.MesaUtilService.IMesaUtilService
    {
        
        public MesaUtilServiceClient()
        {
        }
        
        public MesaUtilServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaUtilServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaUtilServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaUtilServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int CalcularIdade(System.DateTime dataNascimento)
        {
            return base.Channel.CalcularIdade(dataNascimento);
        }
        
        public System.Threading.Tasks.Task<int> CalcularIdadeAsync(System.DateTime dataNascimento)
        {
            return base.Channel.CalcularIdadeAsync(dataNascimento);
        }
        
        public System.Collections.Generic.Dictionary<int, int> CalcularTempoServico(System.DateTime dataAdmissao)
        {
            return base.Channel.CalcularTempoServico(dataAdmissao);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, int>> CalcularTempoServicoAsync(System.DateTime dataAdmissao)
        {
            return base.Channel.CalcularTempoServicoAsync(dataAdmissao);
        }
        
        public bool ValidarCep(string cep)
        {
            return base.Channel.ValidarCep(cep);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCepAsync(string cep)
        {
            return base.Channel.ValidarCepAsync(cep);
        }
        
        public ServicesReference.MesaUtilService.Endereco ObterEndereco(string cep)
        {
            return base.Channel.ObterEndereco(cep);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaUtilService.Endereco> ObterEnderecoAsync(string cep)
        {
            return base.Channel.ObterEnderecoAsync(cep);
        }
        
        public bool ValidarCpf(string cpf)
        {
            return base.Channel.ValidarCpf(cpf);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCpfAsync(string cpf)
        {
            return base.Channel.ValidarCpfAsync(cpf);
        }
        
        public bool ValidarCnpj(string cnpj)
        {
            return base.Channel.ValidarCnpj(cnpj);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCnpjAsync(string cnpj)
        {
            return base.Channel.ValidarCnpjAsync(cnpj);
        }
        
        public ServicesReference.MesaUtilService.Parametro1 ObterParametro(ServicesReference.MesaUtilService.Parametro idParametro)
        {
            return base.Channel.ObterParametro(idParametro);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaUtilService.Parametro1> ObterParametroAsync(ServicesReference.MesaUtilService.Parametro idParametro)
        {
            return base.Channel.ObterParametroAsync(idParametro);
        }
        
        public ServicesReference.MesaUtilService.Renda ValidarRenda(decimal renda, bool rendaObrigatorio, ServicesReference.MesaUtilService.TipoRenda tipoRenda)
        {
            return base.Channel.ValidarRenda(renda, rendaObrigatorio, tipoRenda);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaUtilService.Renda> ValidarRendaAsync(decimal renda, bool rendaObrigatorio, ServicesReference.MesaUtilService.TipoRenda tipoRenda)
        {
            return base.Channel.ValidarRendaAsync(renda, rendaObrigatorio, tipoRenda);
        }
        
        public int[] ObterHorasMesa(string agendamento)
        {
            return base.Channel.ObterHorasMesa(agendamento);
        }
        
        public System.Threading.Tasks.Task<int[]> ObterHorasMesaAsync(string agendamento)
        {
            return base.Channel.ObterHorasMesaAsync(agendamento);
        }
        
        public System.DateTime ObterHoraAgendamento(int tempo)
        {
            return base.Channel.ObterHoraAgendamento(tempo);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> ObterHoraAgendamentoAsync(int tempo)
        {
            return base.Channel.ObterHoraAgendamentoAsync(tempo);
        }
    }
}
