//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaAlertasExternosModalidadeCreditoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModalidadeCredito", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Alert" +
        "asExternos.ModalidadeCredito")]
    public partial class ModalidadeCredito : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private string DescricaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaAlertasExternosModalidadeCreditoService.IMesaAlertasExterno" +
        "sModalidadeCreditoService")]
    public interface IMesaAlertasExternosModalidadeCreditoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaAlertasExternosModalidadeCreditoService/GetModalidades", ReplyAction="http://tempuri.org/IMesaAlertasExternosModalidadeCreditoService/GetModalidadesRes" +
            "ponse")]
        ServicesReference.MesaAlertasExternosModalidadeCreditoService.ModalidadeCredito[] GetModalidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaAlertasExternosModalidadeCreditoService/GetModalidades", ReplyAction="http://tempuri.org/IMesaAlertasExternosModalidadeCreditoService/GetModalidadesRes" +
            "ponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaAlertasExternosModalidadeCreditoService.ModalidadeCredito[]> GetModalidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaAlertasExternosModalidadeCreditoService/GetModalidade", ReplyAction="http://tempuri.org/IMesaAlertasExternosModalidadeCreditoService/GetModalidadeResp" +
            "onse")]
        ServicesReference.MesaAlertasExternosModalidadeCreditoService.ModalidadeCredito GetModalidade(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaAlertasExternosModalidadeCreditoService/GetModalidade", ReplyAction="http://tempuri.org/IMesaAlertasExternosModalidadeCreditoService/GetModalidadeResp" +
            "onse")]
        System.Threading.Tasks.Task<ServicesReference.MesaAlertasExternosModalidadeCreditoService.ModalidadeCredito> GetModalidadeAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaAlertasExternosModalidadeCreditoServiceChannel : ServicesReference.MesaAlertasExternosModalidadeCreditoService.IMesaAlertasExternosModalidadeCreditoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaAlertasExternosModalidadeCreditoServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaAlertasExternosModalidadeCreditoService.IMesaAlertasExternosModalidadeCreditoService>, ServicesReference.MesaAlertasExternosModalidadeCreditoService.IMesaAlertasExternosModalidadeCreditoService
    {
        
        public MesaAlertasExternosModalidadeCreditoServiceClient()
        {
        }
        
        public MesaAlertasExternosModalidadeCreditoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaAlertasExternosModalidadeCreditoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaAlertasExternosModalidadeCreditoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaAlertasExternosModalidadeCreditoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaAlertasExternosModalidadeCreditoService.ModalidadeCredito[] GetModalidades()
        {
            return base.Channel.GetModalidades();
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaAlertasExternosModalidadeCreditoService.ModalidadeCredito[]> GetModalidadesAsync()
        {
            return base.Channel.GetModalidadesAsync();
        }
        
        public ServicesReference.MesaAlertasExternosModalidadeCreditoService.ModalidadeCredito GetModalidade(int codigo)
        {
            return base.Channel.GetModalidade(codigo);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaAlertasExternosModalidadeCreditoService.ModalidadeCredito> GetModalidadeAsync(int codigo)
        {
            return base.Channel.GetModalidadeAsync(codigo);
        }
    }
}
