//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaConsultasExternasComprotService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPessoaEnum", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum TipoPessoaEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisaoGeral = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Proponente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avalista = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conjuge = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cnpj = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comprot", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Comprot")]
    public partial class Comprot : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescricaoField;
        
        private System.DateTime DtMovimentoField;
        
        private string EmpresaField;
        
        private string OrgaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtMovimento
        {
            get
            {
                return this.DtMovimentoField;
            }
            set
            {
                this.DtMovimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Orgao
        {
            get
            {
                return this.OrgaoField;
            }
            set
            {
                this.OrgaoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaConsultasExternasComprotService.IMesaConsultasExternasCompr" +
        "otService")]
    public interface IMesaConsultasExternasComprotService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasComprotService/GetComprot", ReplyAction="http://tempuri.org/IMesaConsultasExternasComprotService/GetComprotResponse")]
        ServicesReference.MesaConsultasExternasComprotService.Comprot[] GetComprot(string idProposta, ServicesReference.MesaConsultasExternasComprotService.TipoPessoaEnum tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasComprotService/GetComprot", ReplyAction="http://tempuri.org/IMesaConsultasExternasComprotService/GetComprotResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasComprotService.Comprot[]> GetComprotAsync(string idProposta, ServicesReference.MesaConsultasExternasComprotService.TipoPessoaEnum tipoPessoa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaConsultasExternasComprotServiceChannel : ServicesReference.MesaConsultasExternasComprotService.IMesaConsultasExternasComprotService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaConsultasExternasComprotServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaConsultasExternasComprotService.IMesaConsultasExternasComprotService>, ServicesReference.MesaConsultasExternasComprotService.IMesaConsultasExternasComprotService
    {
        
        public MesaConsultasExternasComprotServiceClient()
        {
        }
        
        public MesaConsultasExternasComprotServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaConsultasExternasComprotServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasComprotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasComprotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaConsultasExternasComprotService.Comprot[] GetComprot(string idProposta, ServicesReference.MesaConsultasExternasComprotService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetComprot(idProposta, tipoPessoa);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasComprotService.Comprot[]> GetComprotAsync(string idProposta, ServicesReference.MesaConsultasExternasComprotService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetComprotAsync(idProposta, tipoPessoa);
        }
    }
}
