//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaContatoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contato", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Conta" +
        "to")]
    public partial class Contato : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DiretorCodigoField;
        
        private string DiretorFuncaoField;
        
        private string DiretorNomeField;
        
        private string DiretorTelefoneDddField;
        
        private string DiretorTelefoneNumeroField;
        
        private string GerenteCodigoField;
        
        private string GerenteFuncaoField;
        
        private string GerenteNomeField;
        
        private string GerenteTelefoneDddField;
        
        private string GerenteTelefoneNumeroField;
        
        private string OperadorCodigoField;
        
        private string OperadorFuncaoField;
        
        private string OperadorNomeField;
        
        private string OperadorTelefoneDddField;
        
        private string OperadorTelefoneNumeroField;
        
        private string RegionalCodigoField;
        
        private string RegionalFuncaoField;
        
        private string RegionalNomeField;
        
        private string RegionalTelefoneDddField;
        
        private string RegionalTelefoneNumeroField;
        
        private string RevendaCodigoField;
        
        private string RevendaNomeAbreviadoField;
        
        private string RevendaTelefoneDddField;
        
        private string RevendaTelefoneNumeroField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiretorCodigo
        {
            get
            {
                return this.DiretorCodigoField;
            }
            set
            {
                this.DiretorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiretorFuncao
        {
            get
            {
                return this.DiretorFuncaoField;
            }
            set
            {
                this.DiretorFuncaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiretorNome
        {
            get
            {
                return this.DiretorNomeField;
            }
            set
            {
                this.DiretorNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiretorTelefoneDdd
        {
            get
            {
                return this.DiretorTelefoneDddField;
            }
            set
            {
                this.DiretorTelefoneDddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiretorTelefoneNumero
        {
            get
            {
                return this.DiretorTelefoneNumeroField;
            }
            set
            {
                this.DiretorTelefoneNumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GerenteCodigo
        {
            get
            {
                return this.GerenteCodigoField;
            }
            set
            {
                this.GerenteCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GerenteFuncao
        {
            get
            {
                return this.GerenteFuncaoField;
            }
            set
            {
                this.GerenteFuncaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GerenteNome
        {
            get
            {
                return this.GerenteNomeField;
            }
            set
            {
                this.GerenteNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GerenteTelefoneDdd
        {
            get
            {
                return this.GerenteTelefoneDddField;
            }
            set
            {
                this.GerenteTelefoneDddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GerenteTelefoneNumero
        {
            get
            {
                return this.GerenteTelefoneNumeroField;
            }
            set
            {
                this.GerenteTelefoneNumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperadorCodigo
        {
            get
            {
                return this.OperadorCodigoField;
            }
            set
            {
                this.OperadorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperadorFuncao
        {
            get
            {
                return this.OperadorFuncaoField;
            }
            set
            {
                this.OperadorFuncaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperadorNome
        {
            get
            {
                return this.OperadorNomeField;
            }
            set
            {
                this.OperadorNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperadorTelefoneDdd
        {
            get
            {
                return this.OperadorTelefoneDddField;
            }
            set
            {
                this.OperadorTelefoneDddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperadorTelefoneNumero
        {
            get
            {
                return this.OperadorTelefoneNumeroField;
            }
            set
            {
                this.OperadorTelefoneNumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionalCodigo
        {
            get
            {
                return this.RegionalCodigoField;
            }
            set
            {
                this.RegionalCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionalFuncao
        {
            get
            {
                return this.RegionalFuncaoField;
            }
            set
            {
                this.RegionalFuncaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionalNome
        {
            get
            {
                return this.RegionalNomeField;
            }
            set
            {
                this.RegionalNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionalTelefoneDdd
        {
            get
            {
                return this.RegionalTelefoneDddField;
            }
            set
            {
                this.RegionalTelefoneDddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionalTelefoneNumero
        {
            get
            {
                return this.RegionalTelefoneNumeroField;
            }
            set
            {
                this.RegionalTelefoneNumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevendaCodigo
        {
            get
            {
                return this.RevendaCodigoField;
            }
            set
            {
                this.RevendaCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevendaNomeAbreviado
        {
            get
            {
                return this.RevendaNomeAbreviadoField;
            }
            set
            {
                this.RevendaNomeAbreviadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevendaTelefoneDdd
        {
            get
            {
                return this.RevendaTelefoneDddField;
            }
            set
            {
                this.RevendaTelefoneDddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevendaTelefoneNumero
        {
            get
            {
                return this.RevendaTelefoneNumeroField;
            }
            set
            {
                this.RevendaTelefoneNumeroField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaContatoService.IMesaContatoService")]
    public interface IMesaContatoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaContatoService/GetContato", ReplyAction="http://tempuri.org/IMesaContatoService/GetContatoResponse")]
        ServicesReference.MesaContatoService.Contato GetContato(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaContatoService/GetContato", ReplyAction="http://tempuri.org/IMesaContatoService/GetContatoResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaContatoService.Contato> GetContatoAsync(string idProposta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaContatoServiceChannel : ServicesReference.MesaContatoService.IMesaContatoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaContatoServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaContatoService.IMesaContatoService>, ServicesReference.MesaContatoService.IMesaContatoService
    {
        
        public MesaContatoServiceClient()
        {
        }
        
        public MesaContatoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaContatoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaContatoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaContatoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaContatoService.Contato GetContato(string idProposta)
        {
            return base.Channel.GetContato(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaContatoService.Contato> GetContatoAsync(string idProposta)
        {
            return base.Channel.GetContatoAsync(idProposta);
        }
    }
}
