//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaConsultasExternasSerasaService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPessoaEnum", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum TipoPessoaEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisaoGeral = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Proponente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avalista = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conjuge = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cnpj = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Serasa", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Serasa")]
    public partial class Serasa : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ServicesReference.MesaConsultasExternasSerasaService.SerasaRestricao[] RestricoesField;
        
        private ServicesReference.MesaConsultasExternasSerasaService.SerasaTotal TotalField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasSerasaService.SerasaRestricao[] Restricoes
        {
            get
            {
                return this.RestricoesField;
            }
            set
            {
                this.RestricoesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasSerasaService.SerasaTotal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerasaTotal", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Serasa")]
    public partial class SerasaTotal : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ParticipacaoFalenciaField;
        
        private int QtdChequesSemFundoField;
        
        private decimal TotalAcoesField;
        
        private decimal TotalDividasVencidasField;
        
        private decimal TotalPefinField;
        
        private decimal TotalRefinField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParticipacaoFalencia
        {
            get
            {
                return this.ParticipacaoFalenciaField;
            }
            set
            {
                this.ParticipacaoFalenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdChequesSemFundo
        {
            get
            {
                return this.QtdChequesSemFundoField;
            }
            set
            {
                this.QtdChequesSemFundoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAcoes
        {
            get
            {
                return this.TotalAcoesField;
            }
            set
            {
                this.TotalAcoesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDividasVencidas
        {
            get
            {
                return this.TotalDividasVencidasField;
            }
            set
            {
                this.TotalDividasVencidasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPefin
        {
            get
            {
                return this.TotalPefinField;
            }
            set
            {
                this.TotalPefinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalRefin
        {
            get
            {
                return this.TotalRefinField;
            }
            set
            {
                this.TotalRefinField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerasaRestricao", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Serasa")]
    public partial class SerasaRestricao : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DataField;
        
        private string InstituicaoField;
        
        private string ModalidadeField;
        
        private decimal ValorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instituicao
        {
            get
            {
                return this.InstituicaoField;
            }
            set
            {
                this.InstituicaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modalidade
        {
            get
            {
                return this.ModalidadeField;
            }
            set
            {
                this.ModalidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaConsultasExternasSerasaService.IMesaConsultasExternasSerasa" +
        "Service")]
    public interface IMesaConsultasExternasSerasaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasSerasaService/GetSerasa", ReplyAction="http://tempuri.org/IMesaConsultasExternasSerasaService/GetSerasaResponse")]
        ServicesReference.MesaConsultasExternasSerasaService.Serasa GetSerasa(string idProposta, ServicesReference.MesaConsultasExternasSerasaService.TipoPessoaEnum tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasSerasaService/GetSerasa", ReplyAction="http://tempuri.org/IMesaConsultasExternasSerasaService/GetSerasaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasSerasaService.Serasa> GetSerasaAsync(string idProposta, ServicesReference.MesaConsultasExternasSerasaService.TipoPessoaEnum tipoPessoa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaConsultasExternasSerasaServiceChannel : ServicesReference.MesaConsultasExternasSerasaService.IMesaConsultasExternasSerasaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaConsultasExternasSerasaServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaConsultasExternasSerasaService.IMesaConsultasExternasSerasaService>, ServicesReference.MesaConsultasExternasSerasaService.IMesaConsultasExternasSerasaService
    {
        
        public MesaConsultasExternasSerasaServiceClient()
        {
        }
        
        public MesaConsultasExternasSerasaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaConsultasExternasSerasaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasSerasaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasSerasaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaConsultasExternasSerasaService.Serasa GetSerasa(string idProposta, ServicesReference.MesaConsultasExternasSerasaService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetSerasa(idProposta, tipoPessoa);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasSerasaService.Serasa> GetSerasaAsync(string idProposta, ServicesReference.MesaConsultasExternasSerasaService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetSerasaAsync(idProposta, tipoPessoa);
        }
    }
}
