//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaConsultasExternasBureauSimilaridadeService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPessoaEnum", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum TipoPessoaEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisaoGeral = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Proponente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avalista = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conjuge = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cnpj = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BureauSimilaridade", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Bureaus.Similaridade")]
    public partial class BureauSimilaridade : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrdemField;
        
        private string SimilaridadeField;
        
        private ServicesReference.MesaConsultasExternasBureauSimilaridadeService.BureauSimilaridadeValor[] ValoresField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordem
        {
            get
            {
                return this.OrdemField;
            }
            set
            {
                this.OrdemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Similaridade
        {
            get
            {
                return this.SimilaridadeField;
            }
            set
            {
                this.SimilaridadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasBureauSimilaridadeService.BureauSimilaridadeValor[] Valores
        {
            get
            {
                return this.ValoresField;
            }
            set
            {
                this.ValoresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BureauSimilaridadeValor", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Bureaus.Similaridade")]
    public partial class BureauSimilaridadeValor : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string OrigemField;
        
        private string ValorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origem
        {
            get
            {
                return this.OrigemField;
            }
            set
            {
                this.OrigemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaConsultasExternasBureauSimilaridadeService.IMesaConsultasEx" +
        "ternasBureauSimilaridadeService")]
    public interface IMesaConsultasExternasBureauSimilaridadeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasBureauSimilaridadeService/GetBureauSimil" +
            "aridades", ReplyAction="http://tempuri.org/IMesaConsultasExternasBureauSimilaridadeService/GetBureauSimil" +
            "aridadesResponse")]
        ServicesReference.MesaConsultasExternasBureauSimilaridadeService.BureauSimilaridade[] GetBureauSimilaridades(string idProposta, ServicesReference.MesaConsultasExternasBureauSimilaridadeService.TipoPessoaEnum tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasBureauSimilaridadeService/GetBureauSimil" +
            "aridades", ReplyAction="http://tempuri.org/IMesaConsultasExternasBureauSimilaridadeService/GetBureauSimil" +
            "aridadesResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasBureauSimilaridadeService.BureauSimilaridade[]> GetBureauSimilaridadesAsync(string idProposta, ServicesReference.MesaConsultasExternasBureauSimilaridadeService.TipoPessoaEnum tipoPessoa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaConsultasExternasBureauSimilaridadeServiceChannel : ServicesReference.MesaConsultasExternasBureauSimilaridadeService.IMesaConsultasExternasBureauSimilaridadeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaConsultasExternasBureauSimilaridadeServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaConsultasExternasBureauSimilaridadeService.IMesaConsultasExternasBureauSimilaridadeService>, ServicesReference.MesaConsultasExternasBureauSimilaridadeService.IMesaConsultasExternasBureauSimilaridadeService
    {
        
        public MesaConsultasExternasBureauSimilaridadeServiceClient()
        {
        }
        
        public MesaConsultasExternasBureauSimilaridadeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaConsultasExternasBureauSimilaridadeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasBureauSimilaridadeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasBureauSimilaridadeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaConsultasExternasBureauSimilaridadeService.BureauSimilaridade[] GetBureauSimilaridades(string idProposta, ServicesReference.MesaConsultasExternasBureauSimilaridadeService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetBureauSimilaridades(idProposta, tipoPessoa);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasBureauSimilaridadeService.BureauSimilaridade[]> GetBureauSimilaridadesAsync(string idProposta, ServicesReference.MesaConsultasExternasBureauSimilaridadeService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetBureauSimilaridadesAsync(idProposta, tipoPessoa);
        }
    }
}
