//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaAlertasExternosInconsistenciaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inconsistencia", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Alert" +
        "asExternos.Inconsistencia")]
    public partial class Inconsistencia : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private string DescricaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaAlertasExternosInconsistenciaService.IMesaAlertasExternosIn" +
        "consistenciaService")]
    public interface IMesaAlertasExternosInconsistenciaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaAlertasExternosInconsistenciaService/GetInconsistencias", ReplyAction="http://tempuri.org/IMesaAlertasExternosInconsistenciaService/GetInconsistenciasRe" +
            "sponse")]
        ServicesReference.MesaAlertasExternosInconsistenciaService.Inconsistencia[] GetInconsistencias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaAlertasExternosInconsistenciaService/GetInconsistencias", ReplyAction="http://tempuri.org/IMesaAlertasExternosInconsistenciaService/GetInconsistenciasRe" +
            "sponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaAlertasExternosInconsistenciaService.Inconsistencia[]> GetInconsistenciasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaAlertasExternosInconsistenciaService/GetInconsistencia", ReplyAction="http://tempuri.org/IMesaAlertasExternosInconsistenciaService/GetInconsistenciaRes" +
            "ponse")]
        ServicesReference.MesaAlertasExternosInconsistenciaService.Inconsistencia GetInconsistencia(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaAlertasExternosInconsistenciaService/GetInconsistencia", ReplyAction="http://tempuri.org/IMesaAlertasExternosInconsistenciaService/GetInconsistenciaRes" +
            "ponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaAlertasExternosInconsistenciaService.Inconsistencia> GetInconsistenciaAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaAlertasExternosInconsistenciaServiceChannel : ServicesReference.MesaAlertasExternosInconsistenciaService.IMesaAlertasExternosInconsistenciaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaAlertasExternosInconsistenciaServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaAlertasExternosInconsistenciaService.IMesaAlertasExternosInconsistenciaService>, ServicesReference.MesaAlertasExternosInconsistenciaService.IMesaAlertasExternosInconsistenciaService
    {
        
        public MesaAlertasExternosInconsistenciaServiceClient()
        {
        }
        
        public MesaAlertasExternosInconsistenciaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaAlertasExternosInconsistenciaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaAlertasExternosInconsistenciaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaAlertasExternosInconsistenciaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaAlertasExternosInconsistenciaService.Inconsistencia[] GetInconsistencias()
        {
            return base.Channel.GetInconsistencias();
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaAlertasExternosInconsistenciaService.Inconsistencia[]> GetInconsistenciasAsync()
        {
            return base.Channel.GetInconsistenciasAsync();
        }
        
        public ServicesReference.MesaAlertasExternosInconsistenciaService.Inconsistencia GetInconsistencia(int codigo)
        {
            return base.Channel.GetInconsistencia(codigo);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaAlertasExternosInconsistenciaService.Inconsistencia> GetInconsistenciaAsync(int codigo)
        {
            return base.Channel.GetInconsistenciaAsync(codigo);
        }
    }
}
