//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaConsultasExternasBureauParentescosService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BureauParentesco", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Bureaus.Parentesco")]
    public partial class BureauParentesco : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CpfField;
        
        private string FonteField;
        
        private string NomeField;
        
        private string VinculoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf
        {
            get
            {
                return this.CpfField;
            }
            set
            {
                this.CpfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fonte
        {
            get
            {
                return this.FonteField;
            }
            set
            {
                this.FonteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vinculo
        {
            get
            {
                return this.VinculoField;
            }
            set
            {
                this.VinculoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaConsultasExternasBureauParentescosService.IMesaConsultasExt" +
        "ernasBureauParentescosService")]
    public interface IMesaConsultasExternasBureauParentescosService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasBureauParentescosService/GetBureauParent" +
            "escos", ReplyAction="http://tempuri.org/IMesaConsultasExternasBureauParentescosService/GetBureauParent" +
            "escosResponse")]
        ServicesReference.MesaConsultasExternasBureauParentescosService.BureauParentesco[] GetBureauParentescos(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasBureauParentescosService/GetBureauParent" +
            "escos", ReplyAction="http://tempuri.org/IMesaConsultasExternasBureauParentescosService/GetBureauParent" +
            "escosResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasBureauParentescosService.BureauParentesco[]> GetBureauParentescosAsync(string idProposta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaConsultasExternasBureauParentescosServiceChannel : ServicesReference.MesaConsultasExternasBureauParentescosService.IMesaConsultasExternasBureauParentescosService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaConsultasExternasBureauParentescosServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaConsultasExternasBureauParentescosService.IMesaConsultasExternasBureauParentescosService>, ServicesReference.MesaConsultasExternasBureauParentescosService.IMesaConsultasExternasBureauParentescosService
    {
        
        public MesaConsultasExternasBureauParentescosServiceClient()
        {
        }
        
        public MesaConsultasExternasBureauParentescosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaConsultasExternasBureauParentescosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasBureauParentescosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasBureauParentescosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaConsultasExternasBureauParentescosService.BureauParentesco[] GetBureauParentescos(string idProposta)
        {
            return base.Channel.GetBureauParentescos(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasBureauParentescosService.BureauParentesco[]> GetBureauParentescosAsync(string idProposta)
        {
            return base.Channel.GetBureauParentescosAsync(idProposta);
        }
    }
}
