//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaLogService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogHistorico", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class LogHistorico : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AlertaField;
        
        private string AnteriorField;
        
        private ServicesReference.MesaLogService.AlertaAviso[] AvisosField;
        
        private string CampoField;
        
        private string CompromissoField;
        
        private System.Nullable<System.DateTime> DtAgendamentoField;
        
        private System.DateTime DtAlteracaoField;
        
        private System.Nullable<System.DateTime> DtInclusaoField;
        
        private bool EdicaoAtualField;
        
        private string[] MotivosField;
        
        private string NovoField;
        
        private string ParecerComercialField;
        
        private string ParecerDescricaoField;
        
        private string ParecerInternoField;
        
        private int TempoAdicionadoField;
        
        private string UsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alerta
        {
            get
            {
                return this.AlertaField;
            }
            set
            {
                this.AlertaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anterior
        {
            get
            {
                return this.AnteriorField;
            }
            set
            {
                this.AnteriorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaLogService.AlertaAviso[] Avisos
        {
            get
            {
                return this.AvisosField;
            }
            set
            {
                this.AvisosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo
        {
            get
            {
                return this.CampoField;
            }
            set
            {
                this.CampoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Compromisso
        {
            get
            {
                return this.CompromissoField;
            }
            set
            {
                this.CompromissoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DtAgendamento
        {
            get
            {
                return this.DtAgendamentoField;
            }
            set
            {
                this.DtAgendamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtAlteracao
        {
            get
            {
                return this.DtAlteracaoField;
            }
            set
            {
                this.DtAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DtInclusao
        {
            get
            {
                return this.DtInclusaoField;
            }
            set
            {
                this.DtInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EdicaoAtual
        {
            get
            {
                return this.EdicaoAtualField;
            }
            set
            {
                this.EdicaoAtualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Motivos
        {
            get
            {
                return this.MotivosField;
            }
            set
            {
                this.MotivosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Novo
        {
            get
            {
                return this.NovoField;
            }
            set
            {
                this.NovoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParecerComercial
        {
            get
            {
                return this.ParecerComercialField;
            }
            set
            {
                this.ParecerComercialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParecerDescricao
        {
            get
            {
                return this.ParecerDescricaoField;
            }
            set
            {
                this.ParecerDescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParecerInterno
        {
            get
            {
                return this.ParecerInternoField;
            }
            set
            {
                this.ParecerInternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TempoAdicionado
        {
            get
            {
                return this.TempoAdicionadoField;
            }
            set
            {
                this.TempoAdicionadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertaAviso", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Alert" +
        "asExternos.Alertas")]
    public partial class AlertaAviso : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescricaoField;
        
        private int TipoDadoField;
        
        private string ValorField;
        
        private string ValorComplementarField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDado
        {
            get
            {
                return this.TipoDadoField;
            }
            set
            {
                this.TipoDadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorComplementar
        {
            get
            {
                return this.ValorComplementarField;
            }
            set
            {
                this.ValorComplementarField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaLogService.IMesaLogService")]
    public interface IMesaLogService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaLogService/ListarHistorico", ReplyAction="http://tempuri.org/IMesaLogService/ListarHistoricoResponse")]
        ServicesReference.MesaLogService.LogHistorico[] ListarHistorico(string idProposta, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaLogService/ListarHistorico", ReplyAction="http://tempuri.org/IMesaLogService/ListarHistoricoResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaLogService.LogHistorico[]> ListarHistoricoAsync(string idProposta, string guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaLogServiceChannel : ServicesReference.MesaLogService.IMesaLogService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaLogServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaLogService.IMesaLogService>, ServicesReference.MesaLogService.IMesaLogService
    {
        
        public MesaLogServiceClient()
        {
        }
        
        public MesaLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaLogService.LogHistorico[] ListarHistorico(string idProposta, string guid)
        {
            return base.Channel.ListarHistorico(idProposta, guid);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaLogService.LogHistorico[]> ListarHistoricoAsync(string idProposta, string guid)
        {
            return base.Channel.ListarHistoricoAsync(idProposta, guid);
        }
    }
}
