//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaPropostaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropostaAlerta", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class PropostaAlerta : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AlertaField;
        
        private int ResolvidoField;
        
        private int RestanteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Alerta
        {
            get
            {
                return this.AlertaField;
            }
            set
            {
                this.AlertaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Resolvido
        {
            get
            {
                return this.ResolvidoField;
            }
            set
            {
                this.ResolvidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Restante
        {
            get
            {
                return this.RestanteField;
            }
            set
            {
                this.RestanteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropostaConceito", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class PropostaConceito : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ConceitoField;
        
        private decimal PerdaEsperadaField;
        
        private string ScoreField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conceito
        {
            get
            {
                return this.ConceitoField;
            }
            set
            {
                this.ConceitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PerdaEsperada
        {
            get
            {
                return this.PerdaEsperadaField;
            }
            set
            {
                this.PerdaEsperadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropostaStatus", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class PropostaStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdPropostaField;
        
        private string StatusField;
        
        private System.Nullable<System.DateTime> UltimaAnaliseField;
        
        private string UltimoUsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProposta
        {
            get
            {
                return this.IdPropostaField;
            }
            set
            {
                this.IdPropostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UltimaAnalise
        {
            get
            {
                return this.UltimaAnaliseField;
            }
            set
            {
                this.UltimaAnaliseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UltimoUsuario
        {
            get
            {
                return this.UltimoUsuarioField;
            }
            set
            {
                this.UltimoUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImagemApresentacao", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ImagemApresentacao : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string dataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoCivil", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class EstadoCivil : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsEstadoCivilField;
        
        private int IdEstadoCivilField;
        
        private string StCasadoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsEstadoCivil
        {
            get
            {
                return this.DsEstadoCivilField;
            }
            set
            {
                this.DsEstadoCivilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadoCivil
        {
            get
            {
                return this.IdEstadoCivilField;
            }
            set
            {
                this.IdEstadoCivilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StCasado
        {
            get
            {
                return this.StCasadoField;
            }
            set
            {
                this.StCasadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaixasPatrimonio", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class FaixasPatrimonio : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsClienteFaixaPatrimonioField;
        
        private int IdClienteFaixaPatrimonioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsClienteFaixaPatrimonio
        {
            get
            {
                return this.DsClienteFaixaPatrimonioField;
            }
            set
            {
                this.DsClienteFaixaPatrimonioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdClienteFaixaPatrimonio
        {
            get
            {
                return this.IdClienteFaixaPatrimonioField;
            }
            set
            {
                this.IdClienteFaixaPatrimonioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NaturezaOcupacao", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class NaturezaOcupacao : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsNatOcupacaoField;
        
        private int IdNatOcupacaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsNatOcupacao
        {
            get
            {
                return this.DsNatOcupacaoField;
            }
            set
            {
                this.DsNatOcupacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNatOcupacao
        {
            get
            {
                return this.IdNatOcupacaoField;
            }
            set
            {
                this.IdNatOcupacaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sexo", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class Sexo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsSexoField;
        
        private string IdSexoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsSexo
        {
            get
            {
                return this.DsSexoField;
            }
            set
            {
                this.DsSexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSexo
        {
            get
            {
                return this.IdSexoField;
            }
            set
            {
                this.IdSexoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profissao", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class Profissao : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsProfissaoField;
        
        private int IdProfissaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsProfissao
        {
            get
            {
                return this.DsProfissaoField;
            }
            set
            {
                this.DsProfissaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProfissao
        {
            get
            {
                return this.IdProfissaoField;
            }
            set
            {
                this.IdProfissaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cargo", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class Cargo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsCargoField;
        
        private int IdCargoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsCargo
        {
            get
            {
                return this.DsCargoField;
            }
            set
            {
                this.DsCargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCargo
        {
            get
            {
                return this.IdCargoField;
            }
            set
            {
                this.IdCargoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nacionalidade", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class Nacionalidade : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsNacionalidadeField;
        
        private int IdNacionalidadeField;
        
        private bool NacionalidadeDefaultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsNacionalidade
        {
            get
            {
                return this.DsNacionalidadeField;
            }
            set
            {
                this.DsNacionalidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNacionalidade
        {
            get
            {
                return this.IdNacionalidadeField;
            }
            set
            {
                this.IdNacionalidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NacionalidadeDefault
        {
            get
            {
                return this.NacionalidadeDefaultField;
            }
            set
            {
                this.NacionalidadeDefaultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class Estado : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string DescricaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recalcular", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class Recalcular : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdPropostaField;
        
        private string ObservacaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProposta
        {
            get
            {
                return this.IdPropostaField;
            }
            set
            {
                this.IdPropostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao
        {
            get
            {
                return this.ObservacaoField;
            }
            set
            {
                this.ObservacaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerAcao", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerAcao : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsAcaoField;
        
        private int IdAcaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsAcao
        {
            get
            {
                return this.DsAcaoField;
            }
            set
            {
                this.DsAcaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAcao
        {
            get
            {
                return this.IdAcaoField;
            }
            set
            {
                this.IdAcaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerMotivo", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerMotivo : ServicesReference.MesaPropostaService.Parecer
    {
        
        private string DsMotivoField;
        
        private int IdMotivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsMotivo
        {
            get
            {
                return this.DsMotivoField;
            }
            set
            {
                this.DsMotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMotivo
        {
            get
            {
                return this.IdMotivoField;
            }
            set
            {
                this.IdMotivoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parecer", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicesReference.MesaPropostaService.ParecerPendenciar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicesReference.MesaPropostaService.ParecerRecusar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicesReference.MesaPropostaService.ParecerAgendar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicesReference.MesaPropostaService.ParecerAprovar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicesReference.MesaPropostaService.ParecerEncaminhar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicesReference.MesaPropostaService.ParecerMotivo))]
    public partial class Parecer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodUsuarioField;
        
        private int IdAcaoField;
        
        private string IdPropostaField;
        
        private string ObservacaoField;
        
        private string ParecerObservacaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodUsuario
        {
            get
            {
                return this.CodUsuarioField;
            }
            set
            {
                this.CodUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAcao
        {
            get
            {
                return this.IdAcaoField;
            }
            set
            {
                this.IdAcaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProposta
        {
            get
            {
                return this.IdPropostaField;
            }
            set
            {
                this.IdPropostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao
        {
            get
            {
                return this.ObservacaoField;
            }
            set
            {
                this.ObservacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParecerObservacao
        {
            get
            {
                return this.ParecerObservacaoField;
            }
            set
            {
                this.ParecerObservacaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerPendenciar", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerPendenciar : ServicesReference.MesaPropostaService.Parecer
    {
        
        private ServicesReference.MesaPropostaService.ParecerMotivo[] MotivosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaPropostaService.ParecerMotivo[] Motivos
        {
            get
            {
                return this.MotivosField;
            }
            set
            {
                this.MotivosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerRecusar", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerRecusar : ServicesReference.MesaPropostaService.Parecer
    {
        
        private ServicesReference.MesaPropostaService.ParecerMotivo[] MotivosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaPropostaService.ParecerMotivo[] Motivos
        {
            get
            {
                return this.MotivosField;
            }
            set
            {
                this.MotivosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerAgendar", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerAgendar : ServicesReference.MesaPropostaService.Parecer
    {
        
        private System.DateTime DtAgendamentoField;
        
        private int IdMotivoField;
        
        private int TempoAdicionadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtAgendamento
        {
            get
            {
                return this.DtAgendamentoField;
            }
            set
            {
                this.DtAgendamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMotivo
        {
            get
            {
                return this.IdMotivoField;
            }
            set
            {
                this.IdMotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TempoAdicionado
        {
            get
            {
                return this.TempoAdicionadoField;
            }
            set
            {
                this.TempoAdicionadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerAprovar", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerAprovar : ServicesReference.MesaPropostaService.Parecer
    {
        
        private ServicesReference.MesaPropostaService.Pendencia[] PendenciasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaPropostaService.Pendencia[] Pendencias
        {
            get
            {
                return this.PendenciasField;
            }
            set
            {
                this.PendenciasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerEncaminhar", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerEncaminhar : ServicesReference.MesaPropostaService.Parecer
    {
        
        private string CodUsuarioEncField;
        
        private string DsTipoComiteField;
        
        private int IdComiteField;
        
        private int IdMotivoField;
        
        private int IdPrioridadeField;
        
        private string NomeUsuarioField;
        
        private ServicesReference.MesaPropostaService.Pendencia[] PendenciasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodUsuarioEnc
        {
            get
            {
                return this.CodUsuarioEncField;
            }
            set
            {
                this.CodUsuarioEncField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsTipoComite
        {
            get
            {
                return this.DsTipoComiteField;
            }
            set
            {
                this.DsTipoComiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComite
        {
            get
            {
                return this.IdComiteField;
            }
            set
            {
                this.IdComiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMotivo
        {
            get
            {
                return this.IdMotivoField;
            }
            set
            {
                this.IdMotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPrioridade
        {
            get
            {
                return this.IdPrioridadeField;
            }
            set
            {
                this.IdPrioridadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuario
        {
            get
            {
                return this.NomeUsuarioField;
            }
            set
            {
                this.NomeUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaPropostaService.Pendencia[] Pendencias
        {
            get
            {
                return this.PendenciasField;
            }
            set
            {
                this.PendenciasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pendencia", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class Pendencia : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CompromissoField;
        
        private int IdField;
        
        private string PropostaField;
        
        private bool TipoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Compromisso
        {
            get
            {
                return this.CompromissoField;
            }
            set
            {
                this.CompromissoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proposta
        {
            get
            {
                return this.PropostaField;
            }
            set
            {
                this.PropostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerPendencia", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerPendencia : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsPendenciaField;
        
        private bool FlPagamentoField;
        
        private int FlPendenciaField;
        
        private int IdCompromissoField;
        
        private string IdPendenciaField;
        
        private ServicesReference.MesaPropostaService.ParecerAprovarDocumento ObrigatorioPagamentoField;
        
        private int SelFlPendenciaField;
        
        private int SelIdCompromissoField;
        
        private int SelIdPendenciaField;
        
        private int SparePosicaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsPendencia
        {
            get
            {
                return this.DsPendenciaField;
            }
            set
            {
                this.DsPendenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlPagamento
        {
            get
            {
                return this.FlPagamentoField;
            }
            set
            {
                this.FlPagamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlPendencia
        {
            get
            {
                return this.FlPendenciaField;
            }
            set
            {
                this.FlPendenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCompromisso
        {
            get
            {
                return this.IdCompromissoField;
            }
            set
            {
                this.IdCompromissoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPendencia
        {
            get
            {
                return this.IdPendenciaField;
            }
            set
            {
                this.IdPendenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaPropostaService.ParecerAprovarDocumento ObrigatorioPagamento
        {
            get
            {
                return this.ObrigatorioPagamentoField;
            }
            set
            {
                this.ObrigatorioPagamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SelFlPendencia
        {
            get
            {
                return this.SelFlPendenciaField;
            }
            set
            {
                this.SelFlPendenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SelIdCompromisso
        {
            get
            {
                return this.SelIdCompromissoField;
            }
            set
            {
                this.SelIdCompromissoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SelIdPendencia
        {
            get
            {
                return this.SelIdPendenciaField;
            }
            set
            {
                this.SelIdPendenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SparePosicao
        {
            get
            {
                return this.SparePosicaoField;
            }
            set
            {
                this.SparePosicaoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerAprovarDocumento", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum ParecerAprovarDocumento : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreSelecionado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Obrigatorio = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Opcional = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerPrioridade", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerPrioridade : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DsPrioridadeField;
        
        private int IdPrioridadeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsPrioridade
        {
            get
            {
                return this.DsPrioridadeField;
            }
            set
            {
                this.DsPrioridadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPrioridade
        {
            get
            {
                return this.IdPrioridadeField;
            }
            set
            {
                this.IdPrioridadeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerUsuario", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerUsuario : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodUsuarioField;
        
        private string IdPropostaField;
        
        private string NomeUsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodUsuario
        {
            get
            {
                return this.CodUsuarioField;
            }
            set
            {
                this.CodUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProposta
        {
            get
            {
                return this.IdPropostaField;
            }
            set
            {
                this.IdPropostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuario
        {
            get
            {
                return this.NomeUsuarioField;
            }
            set
            {
                this.NomeUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParecerComite", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ParecerComite : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodUsuarioField;
        
        private string DsTipoComiteField;
        
        private int IdComiteField;
        
        private string IdPropostaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodUsuario
        {
            get
            {
                return this.CodUsuarioField;
            }
            set
            {
                this.CodUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DsTipoComite
        {
            get
            {
                return this.DsTipoComiteField;
            }
            set
            {
                this.DsTipoComiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComite
        {
            get
            {
                return this.IdComiteField;
            }
            set
            {
                this.IdComiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProposta
        {
            get
            {
                return this.IdPropostaField;
            }
            set
            {
                this.IdPropostaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProximaProposta", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class ProximaProposta : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdPropostaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProposta
        {
            get
            {
                return this.IdPropostaField;
            }
            set
            {
                this.IdPropostaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoAnalise", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class InfoAnalise : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AlcadaField;
        
        private string TempoAnaliseField;
        
        private string UsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alcada
        {
            get
            {
                return this.AlcadaField;
            }
            set
            {
                this.AlcadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TempoAnalise
        {
            get
            {
                return this.TempoAnaliseField;
            }
            set
            {
                this.TempoAnaliseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CapturaObservacao", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces")]
    public partial class CapturaObservacao : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ObservacaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao
        {
            get
            {
                return this.ObservacaoField;
            }
            set
            {
                this.ObservacaoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaPropostaService.IMesaPropostaService")]
    public interface IMesaPropostaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ObterAlertasProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/ObterAlertasPropostaResponse")]
        ServicesReference.MesaPropostaService.PropostaAlerta ObterAlertasProposta(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ObterAlertasProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/ObterAlertasPropostaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.PropostaAlerta> ObterAlertasPropostaAsync(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ObterConceitoProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/ObterConceitoPropostaResponse")]
        ServicesReference.MesaPropostaService.PropostaConceito ObterConceitoProposta(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ObterConceitoProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/ObterConceitoPropostaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.PropostaConceito> ObterConceitoPropostaAsync(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ObterStatusProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/ObterStatusPropostaResponse")]
        ServicesReference.MesaPropostaService.PropostaStatus ObterStatusProposta(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ObterStatusProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/ObterStatusPropostaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.PropostaStatus> ObterStatusPropostaAsync(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ObterImagemProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/ObterImagemPropostaResponse")]
        ServicesReference.MesaPropostaService.ImagemApresentacao[] ObterImagemProposta(string idProposta, int idModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ObterImagemProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/ObterImagemPropostaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ImagemApresentacao[]> ObterImagemPropostaAsync(string idProposta, int idModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarEstadoCivil", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarEstadoCivilResponse")]
        ServicesReference.MesaPropostaService.EstadoCivil[] ListarEstadoCivil(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarEstadoCivil", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarEstadoCivilResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.EstadoCivil[]> ListarEstadoCivilAsync(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarFaixasPatrimonio", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarFaixasPatrimonioResponse")]
        ServicesReference.MesaPropostaService.FaixasPatrimonio[] ListarFaixasPatrimonio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarFaixasPatrimonio", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarFaixasPatrimonioResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.FaixasPatrimonio[]> ListarFaixasPatrimonioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarNaturezaOcupacao", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarNaturezaOcupacaoResponse")]
        ServicesReference.MesaPropostaService.NaturezaOcupacao[] ListarNaturezaOcupacao(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarNaturezaOcupacao", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarNaturezaOcupacaoResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.NaturezaOcupacao[]> ListarNaturezaOcupacaoAsync(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarSexo", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarSexoResponse")]
        ServicesReference.MesaPropostaService.Sexo[] ListarSexo(bool adicionarNaoInformado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarSexo", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarSexoResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.Sexo[]> ListarSexoAsync(bool adicionarNaoInformado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarProfissoes", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarProfissoesResponse")]
        ServicesReference.MesaPropostaService.Profissao[] ListarProfissoes(int idOcupacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarProfissoes", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarProfissoesResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.Profissao[]> ListarProfissoesAsync(int idOcupacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarCargos", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarCargosResponse")]
        ServicesReference.MesaPropostaService.Cargo[] ListarCargos(int idOcupacao, int idProfissao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarCargos", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarCargosResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.Cargo[]> ListarCargosAsync(int idOcupacao, int idProfissao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarNacionalidades", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarNacionalidadesResponse")]
        ServicesReference.MesaPropostaService.Nacionalidade[] ListarNacionalidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarNacionalidades", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarNacionalidadesResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.Nacionalidade[]> ListarNacionalidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarEstados", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarEstadosResponse")]
        ServicesReference.MesaPropostaService.Estado[] ListarEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarEstados", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarEstadosResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.Estado[]> ListarEstadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/Recalcular", ReplyAction="http://tempuri.org/IMesaPropostaService/RecalcularResponse")]
        bool Recalcular([System.ServiceModel.MessageParameterAttribute(Name="recalcular")] ServicesReference.MesaPropostaService.Recalcular recalcular1, string codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/Recalcular", ReplyAction="http://tempuri.org/IMesaPropostaService/RecalcularResponse")]
        System.Threading.Tasks.Task<bool> RecalcularAsync(ServicesReference.MesaPropostaService.Recalcular recalcular, string codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerAcao", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerAcaoResponse")]
        ServicesReference.MesaPropostaService.ParecerAcao[] ListarParecerAcao(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerAcao", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerAcaoResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerAcao[]> ListarParecerAcaoAsync(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerMotivo", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerMotivoResponse")]
        ServicesReference.MesaPropostaService.ParecerMotivo[] ListarParecerMotivo(int idAcao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerMotivo", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerMotivoResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerMotivo[]> ListarParecerMotivoAsync(int idAcao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerMotivoEncaminhar", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerMotivoEncaminharResponse")]
        ServicesReference.MesaPropostaService.ParecerMotivo[] ListarParecerMotivoEncaminhar(string idProposta, string codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerMotivoEncaminhar", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerMotivoEncaminharResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerMotivo[]> ListarParecerMotivoEncaminharAsync(string idProposta, string codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerPendencia", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerPendenciaResponse")]
        ServicesReference.MesaPropostaService.ParecerPendencia[] ListarParecerPendencia(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerPendencia", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerPendenciaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerPendencia[]> ListarParecerPendenciaAsync(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerPrioridades", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerPrioridadesResponse")]
        ServicesReference.MesaPropostaService.ParecerPrioridade[] ListarParecerPrioridades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerPrioridades", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerPrioridadesResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerPrioridade[]> ListarParecerPrioridadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerUsuario", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerUsuarioResponse")]
        ServicesReference.MesaPropostaService.ParecerUsuario[] ListarParecerUsuario(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerUsuario", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerUsuarioResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerUsuario[]> ListarParecerUsuarioAsync(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerComite", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerComiteResponse")]
        ServicesReference.MesaPropostaService.ParecerComite[] ListarParecerComite(ServicesReference.MesaPropostaService.ParecerComite parecerComite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerComite", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerComiteResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerComite[]> ListarParecerComiteAsync(ServicesReference.MesaPropostaService.ParecerComite parecerComite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerUsuarioRemetente", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerUsuarioRemetenteResponse")]
        ServicesReference.MesaPropostaService.ParecerUsuario[] ListarParecerUsuarioRemetente(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerUsuarioRemetente", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerUsuarioRemetenteResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerUsuario[]> ListarParecerUsuarioRemetenteAsync(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerUsuarioAlcada", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerUsuarioAlcadaResponse")]
        ServicesReference.MesaPropostaService.ParecerUsuario[] ListarParecerUsuarioAlcada(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ListarParecerUsuarioAlcada", ReplyAction="http://tempuri.org/IMesaPropostaService/ListarParecerUsuarioAlcadaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerUsuario[]> ListarParecerUsuarioAlcadaAsync(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ParecerPendenciar", ReplyAction="http://tempuri.org/IMesaPropostaService/ParecerPendenciarResponse")]
        bool ParecerPendenciar(ServicesReference.MesaPropostaService.ParecerPendenciar parecer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ParecerPendenciar", ReplyAction="http://tempuri.org/IMesaPropostaService/ParecerPendenciarResponse")]
        System.Threading.Tasks.Task<bool> ParecerPendenciarAsync(ServicesReference.MesaPropostaService.ParecerPendenciar parecer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ParecerRecusar", ReplyAction="http://tempuri.org/IMesaPropostaService/ParecerRecusarResponse")]
        string[] ParecerRecusar(ServicesReference.MesaPropostaService.ParecerRecusar parecer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ParecerRecusar", ReplyAction="http://tempuri.org/IMesaPropostaService/ParecerRecusarResponse")]
        System.Threading.Tasks.Task<string[]> ParecerRecusarAsync(ServicesReference.MesaPropostaService.ParecerRecusar parecer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ParecerAgendar", ReplyAction="http://tempuri.org/IMesaPropostaService/ParecerAgendarResponse")]
        string[] ParecerAgendar(ServicesReference.MesaPropostaService.ParecerAgendar agendamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ParecerAgendar", ReplyAction="http://tempuri.org/IMesaPropostaService/ParecerAgendarResponse")]
        System.Threading.Tasks.Task<string[]> ParecerAgendarAsync(ServicesReference.MesaPropostaService.ParecerAgendar agendamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ParecerAprovar", ReplyAction="http://tempuri.org/IMesaPropostaService/ParecerAprovarResponse")]
        string[] ParecerAprovar(ServicesReference.MesaPropostaService.ParecerAprovar parecer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ParecerAprovar", ReplyAction="http://tempuri.org/IMesaPropostaService/ParecerAprovarResponse")]
        System.Threading.Tasks.Task<string[]> ParecerAprovarAsync(ServicesReference.MesaPropostaService.ParecerAprovar parecer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/GetProximaProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/GetProximaPropostaResponse")]
        ServicesReference.MesaPropostaService.ProximaProposta GetProximaProposta(string codUsuario, string idPropostaAnterior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/GetProximaProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/GetProximaPropostaResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ProximaProposta> GetProximaPropostaAsync(string codUsuario, string idPropostaAnterior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/SetUsoProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/SetUsoPropostaResponse")]
        bool SetUsoProposta(string idProposta, string codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/SetUsoProposta", ReplyAction="http://tempuri.org/IMesaPropostaService/SetUsoPropostaResponse")]
        System.Threading.Tasks.Task<bool> SetUsoPropostaAsync(string idProposta, string codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/GetInfoAnalise", ReplyAction="http://tempuri.org/IMesaPropostaService/GetInfoAnaliseResponse")]
        ServicesReference.MesaPropostaService.InfoAnalise GetInfoAnalise(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/GetInfoAnalise", ReplyAction="http://tempuri.org/IMesaPropostaService/GetInfoAnaliseResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.InfoAnalise> GetInfoAnaliseAsync(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ParecerEncaminhar", ReplyAction="http://tempuri.org/IMesaPropostaService/ParecerEncaminharResponse")]
        string[] ParecerEncaminhar(ServicesReference.MesaPropostaService.ParecerEncaminhar encaminhar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/ParecerEncaminhar", ReplyAction="http://tempuri.org/IMesaPropostaService/ParecerEncaminharResponse")]
        System.Threading.Tasks.Task<string[]> ParecerEncaminharAsync(ServicesReference.MesaPropostaService.ParecerEncaminhar encaminhar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/GetCapturaObservacao", ReplyAction="http://tempuri.org/IMesaPropostaService/GetCapturaObservacaoResponse")]
        ServicesReference.MesaPropostaService.CapturaObservacao GetCapturaObservacao(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaPropostaService/GetCapturaObservacao", ReplyAction="http://tempuri.org/IMesaPropostaService/GetCapturaObservacaoResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.CapturaObservacao> GetCapturaObservacaoAsync(string idProposta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaPropostaServiceChannel : ServicesReference.MesaPropostaService.IMesaPropostaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaPropostaServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaPropostaService.IMesaPropostaService>, ServicesReference.MesaPropostaService.IMesaPropostaService
    {
        
        public MesaPropostaServiceClient()
        {
        }
        
        public MesaPropostaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaPropostaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaPropostaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaPropostaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaPropostaService.PropostaAlerta ObterAlertasProposta(string idProposta)
        {
            return base.Channel.ObterAlertasProposta(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.PropostaAlerta> ObterAlertasPropostaAsync(string idProposta)
        {
            return base.Channel.ObterAlertasPropostaAsync(idProposta);
        }
        
        public ServicesReference.MesaPropostaService.PropostaConceito ObterConceitoProposta(string idProposta)
        {
            return base.Channel.ObterConceitoProposta(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.PropostaConceito> ObterConceitoPropostaAsync(string idProposta)
        {
            return base.Channel.ObterConceitoPropostaAsync(idProposta);
        }
        
        public ServicesReference.MesaPropostaService.PropostaStatus ObterStatusProposta(string idProposta)
        {
            return base.Channel.ObterStatusProposta(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.PropostaStatus> ObterStatusPropostaAsync(string idProposta)
        {
            return base.Channel.ObterStatusPropostaAsync(idProposta);
        }
        
        public ServicesReference.MesaPropostaService.ImagemApresentacao[] ObterImagemProposta(string idProposta, int idModulo)
        {
            return base.Channel.ObterImagemProposta(idProposta, idModulo);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ImagemApresentacao[]> ObterImagemPropostaAsync(string idProposta, int idModulo)
        {
            return base.Channel.ObterImagemPropostaAsync(idProposta, idModulo);
        }
        
        public ServicesReference.MesaPropostaService.EstadoCivil[] ListarEstadoCivil(string idProposta)
        {
            return base.Channel.ListarEstadoCivil(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.EstadoCivil[]> ListarEstadoCivilAsync(string idProposta)
        {
            return base.Channel.ListarEstadoCivilAsync(idProposta);
        }
        
        public ServicesReference.MesaPropostaService.FaixasPatrimonio[] ListarFaixasPatrimonio()
        {
            return base.Channel.ListarFaixasPatrimonio();
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.FaixasPatrimonio[]> ListarFaixasPatrimonioAsync()
        {
            return base.Channel.ListarFaixasPatrimonioAsync();
        }
        
        public ServicesReference.MesaPropostaService.NaturezaOcupacao[] ListarNaturezaOcupacao(string idProposta)
        {
            return base.Channel.ListarNaturezaOcupacao(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.NaturezaOcupacao[]> ListarNaturezaOcupacaoAsync(string idProposta)
        {
            return base.Channel.ListarNaturezaOcupacaoAsync(idProposta);
        }
        
        public ServicesReference.MesaPropostaService.Sexo[] ListarSexo(bool adicionarNaoInformado)
        {
            return base.Channel.ListarSexo(adicionarNaoInformado);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.Sexo[]> ListarSexoAsync(bool adicionarNaoInformado)
        {
            return base.Channel.ListarSexoAsync(adicionarNaoInformado);
        }
        
        public ServicesReference.MesaPropostaService.Profissao[] ListarProfissoes(int idOcupacao)
        {
            return base.Channel.ListarProfissoes(idOcupacao);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.Profissao[]> ListarProfissoesAsync(int idOcupacao)
        {
            return base.Channel.ListarProfissoesAsync(idOcupacao);
        }
        
        public ServicesReference.MesaPropostaService.Cargo[] ListarCargos(int idOcupacao, int idProfissao)
        {
            return base.Channel.ListarCargos(idOcupacao, idProfissao);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.Cargo[]> ListarCargosAsync(int idOcupacao, int idProfissao)
        {
            return base.Channel.ListarCargosAsync(idOcupacao, idProfissao);
        }
        
        public ServicesReference.MesaPropostaService.Nacionalidade[] ListarNacionalidades()
        {
            return base.Channel.ListarNacionalidades();
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.Nacionalidade[]> ListarNacionalidadesAsync()
        {
            return base.Channel.ListarNacionalidadesAsync();
        }
        
        public ServicesReference.MesaPropostaService.Estado[] ListarEstados()
        {
            return base.Channel.ListarEstados();
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.Estado[]> ListarEstadosAsync()
        {
            return base.Channel.ListarEstadosAsync();
        }
        
        public bool Recalcular(ServicesReference.MesaPropostaService.Recalcular recalcular1, string codUsuario)
        {
            return base.Channel.Recalcular(recalcular1, codUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> RecalcularAsync(ServicesReference.MesaPropostaService.Recalcular recalcular, string codUsuario)
        {
            return base.Channel.RecalcularAsync(recalcular, codUsuario);
        }
        
        public ServicesReference.MesaPropostaService.ParecerAcao[] ListarParecerAcao(string idProposta)
        {
            return base.Channel.ListarParecerAcao(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerAcao[]> ListarParecerAcaoAsync(string idProposta)
        {
            return base.Channel.ListarParecerAcaoAsync(idProposta);
        }
        
        public ServicesReference.MesaPropostaService.ParecerMotivo[] ListarParecerMotivo(int idAcao)
        {
            return base.Channel.ListarParecerMotivo(idAcao);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerMotivo[]> ListarParecerMotivoAsync(int idAcao)
        {
            return base.Channel.ListarParecerMotivoAsync(idAcao);
        }
        
        public ServicesReference.MesaPropostaService.ParecerMotivo[] ListarParecerMotivoEncaminhar(string idProposta, string codUsuario)
        {
            return base.Channel.ListarParecerMotivoEncaminhar(idProposta, codUsuario);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerMotivo[]> ListarParecerMotivoEncaminharAsync(string idProposta, string codUsuario)
        {
            return base.Channel.ListarParecerMotivoEncaminharAsync(idProposta, codUsuario);
        }
        
        public ServicesReference.MesaPropostaService.ParecerPendencia[] ListarParecerPendencia(string idProposta)
        {
            return base.Channel.ListarParecerPendencia(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerPendencia[]> ListarParecerPendenciaAsync(string idProposta)
        {
            return base.Channel.ListarParecerPendenciaAsync(idProposta);
        }
        
        public ServicesReference.MesaPropostaService.ParecerPrioridade[] ListarParecerPrioridades()
        {
            return base.Channel.ListarParecerPrioridades();
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerPrioridade[]> ListarParecerPrioridadesAsync()
        {
            return base.Channel.ListarParecerPrioridadesAsync();
        }
        
        public ServicesReference.MesaPropostaService.ParecerUsuario[] ListarParecerUsuario(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario)
        {
            return base.Channel.ListarParecerUsuario(parecerUsuario);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerUsuario[]> ListarParecerUsuarioAsync(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario)
        {
            return base.Channel.ListarParecerUsuarioAsync(parecerUsuario);
        }
        
        public ServicesReference.MesaPropostaService.ParecerComite[] ListarParecerComite(ServicesReference.MesaPropostaService.ParecerComite parecerComite)
        {
            return base.Channel.ListarParecerComite(parecerComite);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerComite[]> ListarParecerComiteAsync(ServicesReference.MesaPropostaService.ParecerComite parecerComite)
        {
            return base.Channel.ListarParecerComiteAsync(parecerComite);
        }
        
        public ServicesReference.MesaPropostaService.ParecerUsuario[] ListarParecerUsuarioRemetente(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario)
        {
            return base.Channel.ListarParecerUsuarioRemetente(parecerUsuario);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerUsuario[]> ListarParecerUsuarioRemetenteAsync(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario)
        {
            return base.Channel.ListarParecerUsuarioRemetenteAsync(parecerUsuario);
        }
        
        public ServicesReference.MesaPropostaService.ParecerUsuario[] ListarParecerUsuarioAlcada(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario)
        {
            return base.Channel.ListarParecerUsuarioAlcada(parecerUsuario);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ParecerUsuario[]> ListarParecerUsuarioAlcadaAsync(ServicesReference.MesaPropostaService.ParecerUsuario parecerUsuario)
        {
            return base.Channel.ListarParecerUsuarioAlcadaAsync(parecerUsuario);
        }
        
        public bool ParecerPendenciar(ServicesReference.MesaPropostaService.ParecerPendenciar parecer)
        {
            return base.Channel.ParecerPendenciar(parecer);
        }
        
        public System.Threading.Tasks.Task<bool> ParecerPendenciarAsync(ServicesReference.MesaPropostaService.ParecerPendenciar parecer)
        {
            return base.Channel.ParecerPendenciarAsync(parecer);
        }
        
        public string[] ParecerRecusar(ServicesReference.MesaPropostaService.ParecerRecusar parecer)
        {
            return base.Channel.ParecerRecusar(parecer);
        }
        
        public System.Threading.Tasks.Task<string[]> ParecerRecusarAsync(ServicesReference.MesaPropostaService.ParecerRecusar parecer)
        {
            return base.Channel.ParecerRecusarAsync(parecer);
        }
        
        public string[] ParecerAgendar(ServicesReference.MesaPropostaService.ParecerAgendar agendamento)
        {
            return base.Channel.ParecerAgendar(agendamento);
        }
        
        public System.Threading.Tasks.Task<string[]> ParecerAgendarAsync(ServicesReference.MesaPropostaService.ParecerAgendar agendamento)
        {
            return base.Channel.ParecerAgendarAsync(agendamento);
        }
        
        public string[] ParecerAprovar(ServicesReference.MesaPropostaService.ParecerAprovar parecer)
        {
            return base.Channel.ParecerAprovar(parecer);
        }
        
        public System.Threading.Tasks.Task<string[]> ParecerAprovarAsync(ServicesReference.MesaPropostaService.ParecerAprovar parecer)
        {
            return base.Channel.ParecerAprovarAsync(parecer);
        }
        
        public ServicesReference.MesaPropostaService.ProximaProposta GetProximaProposta(string codUsuario, string idPropostaAnterior)
        {
            return base.Channel.GetProximaProposta(codUsuario, idPropostaAnterior);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.ProximaProposta> GetProximaPropostaAsync(string codUsuario, string idPropostaAnterior)
        {
            return base.Channel.GetProximaPropostaAsync(codUsuario, idPropostaAnterior);
        }
        
        public bool SetUsoProposta(string idProposta, string codUsuario)
        {
            return base.Channel.SetUsoProposta(idProposta, codUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> SetUsoPropostaAsync(string idProposta, string codUsuario)
        {
            return base.Channel.SetUsoPropostaAsync(idProposta, codUsuario);
        }
        
        public ServicesReference.MesaPropostaService.InfoAnalise GetInfoAnalise(string idProposta)
        {
            return base.Channel.GetInfoAnalise(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.InfoAnalise> GetInfoAnaliseAsync(string idProposta)
        {
            return base.Channel.GetInfoAnaliseAsync(idProposta);
        }
        
        public string[] ParecerEncaminhar(ServicesReference.MesaPropostaService.ParecerEncaminhar encaminhar)
        {
            return base.Channel.ParecerEncaminhar(encaminhar);
        }
        
        public System.Threading.Tasks.Task<string[]> ParecerEncaminharAsync(ServicesReference.MesaPropostaService.ParecerEncaminhar encaminhar)
        {
            return base.Channel.ParecerEncaminharAsync(encaminhar);
        }
        
        public ServicesReference.MesaPropostaService.CapturaObservacao GetCapturaObservacao(string idProposta)
        {
            return base.Channel.GetCapturaObservacao(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaPropostaService.CapturaObservacao> GetCapturaObservacaoAsync(string idProposta)
        {
            return base.Channel.GetCapturaObservacaoAsync(idProposta);
        }
    }
}
