//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaConsultasExternasCetipService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPessoaEnum", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum TipoPessoaEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisaoGeral = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Proponente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avalista = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conjuge = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cnpj = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cetip", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Cetip")]
    public partial class Cetip : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ServicesReference.MesaConsultasExternasCetipService.CetipFinanciamento[] FinanciamentosField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasCetipService.CetipFinanciamento[] Financiamentos
        {
            get
            {
                return this.FinanciamentosField;
            }
            set
            {
                this.FinanciamentosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CetipFinanciamento", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Cetip")]
    public partial class CetipFinanciamento : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ServicesReference.MesaConsultasExternasCetipService.CetipBem BemField;
        
        private ServicesReference.MesaConsultasExternasCetipService.CetipInstituicao InstituicaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasCetipService.CetipBem Bem
        {
            get
            {
                return this.BemField;
            }
            set
            {
                this.BemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasCetipService.CetipInstituicao Instituicao
        {
            get
            {
                return this.InstituicaoField;
            }
            set
            {
                this.InstituicaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CetipBem", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Cetip")]
    public partial class CetipBem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AnoModeloField;
        
        private string MarcaField;
        
        private string ModeloField;
        
        private int PrazoDecContratoField;
        
        private int PrazoFinSNGField;
        
        private string StatusFinanciamentoField;
        
        private string StatusVeiculoField;
        
        private string TipoAgenteFinanceiroField;
        
        private string TipoGravameField;
        
        private string VeiculoFinanciadoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnoModelo
        {
            get
            {
                return this.AnoModeloField;
            }
            set
            {
                this.AnoModeloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca
        {
            get
            {
                return this.MarcaField;
            }
            set
            {
                this.MarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo
        {
            get
            {
                return this.ModeloField;
            }
            set
            {
                this.ModeloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrazoDecContrato
        {
            get
            {
                return this.PrazoDecContratoField;
            }
            set
            {
                this.PrazoDecContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrazoFinSNG
        {
            get
            {
                return this.PrazoFinSNGField;
            }
            set
            {
                this.PrazoFinSNGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusFinanciamento
        {
            get
            {
                return this.StatusFinanciamentoField;
            }
            set
            {
                this.StatusFinanciamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusVeiculo
        {
            get
            {
                return this.StatusVeiculoField;
            }
            set
            {
                this.StatusVeiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoAgenteFinanceiro
        {
            get
            {
                return this.TipoAgenteFinanceiroField;
            }
            set
            {
                this.TipoAgenteFinanceiroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoGravame
        {
            get
            {
                return this.TipoGravameField;
            }
            set
            {
                this.TipoGravameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VeiculoFinanciado
        {
            get
            {
                return this.VeiculoFinanciadoField;
            }
            set
            {
                this.VeiculoFinanciadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CetipInstituicao", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Cetip")]
    public partial class CetipInstituicao : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AnoAquisicaoVeiculoField;
        
        private string AnoDeixouPertencerCPFField;
        
        private string AutoFinanciamentoField;
        
        private System.DateTime DataBaixaSNGField;
        
        private System.DateTime DataContratoField;
        
        private System.DateTime DataInclusaoSNGField;
        
        private string IdTabelaMercadoField;
        
        private string InstituicaoField;
        
        private decimal ValorAdquiridoVeiculoField;
        
        private decimal ValorAtualVeiculoField;
        
        private decimal ValorFinanciadoPresumidoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnoAquisicaoVeiculo
        {
            get
            {
                return this.AnoAquisicaoVeiculoField;
            }
            set
            {
                this.AnoAquisicaoVeiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnoDeixouPertencerCPF
        {
            get
            {
                return this.AnoDeixouPertencerCPFField;
            }
            set
            {
                this.AnoDeixouPertencerCPFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoFinanciamento
        {
            get
            {
                return this.AutoFinanciamentoField;
            }
            set
            {
                this.AutoFinanciamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataBaixaSNG
        {
            get
            {
                return this.DataBaixaSNGField;
            }
            set
            {
                this.DataBaixaSNGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataContrato
        {
            get
            {
                return this.DataContratoField;
            }
            set
            {
                this.DataContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataInclusaoSNG
        {
            get
            {
                return this.DataInclusaoSNGField;
            }
            set
            {
                this.DataInclusaoSNGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTabelaMercado
        {
            get
            {
                return this.IdTabelaMercadoField;
            }
            set
            {
                this.IdTabelaMercadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instituicao
        {
            get
            {
                return this.InstituicaoField;
            }
            set
            {
                this.InstituicaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorAdquiridoVeiculo
        {
            get
            {
                return this.ValorAdquiridoVeiculoField;
            }
            set
            {
                this.ValorAdquiridoVeiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorAtualVeiculo
        {
            get
            {
                return this.ValorAtualVeiculoField;
            }
            set
            {
                this.ValorAtualVeiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorFinanciadoPresumido
        {
            get
            {
                return this.ValorFinanciadoPresumidoField;
            }
            set
            {
                this.ValorFinanciadoPresumidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaConsultasExternasCetipService.IMesaConsultasExternasCetipSe" +
        "rvice")]
    public interface IMesaConsultasExternasCetipService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasCetipService/GetCetip", ReplyAction="http://tempuri.org/IMesaConsultasExternasCetipService/GetCetipResponse")]
        ServicesReference.MesaConsultasExternasCetipService.Cetip GetCetip(string idProposta, ServicesReference.MesaConsultasExternasCetipService.TipoPessoaEnum tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasCetipService/GetCetip", ReplyAction="http://tempuri.org/IMesaConsultasExternasCetipService/GetCetipResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasCetipService.Cetip> GetCetipAsync(string idProposta, ServicesReference.MesaConsultasExternasCetipService.TipoPessoaEnum tipoPessoa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaConsultasExternasCetipServiceChannel : ServicesReference.MesaConsultasExternasCetipService.IMesaConsultasExternasCetipService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaConsultasExternasCetipServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaConsultasExternasCetipService.IMesaConsultasExternasCetipService>, ServicesReference.MesaConsultasExternasCetipService.IMesaConsultasExternasCetipService
    {
        
        public MesaConsultasExternasCetipServiceClient()
        {
        }
        
        public MesaConsultasExternasCetipServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaConsultasExternasCetipServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasCetipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasCetipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaConsultasExternasCetipService.Cetip GetCetip(string idProposta, ServicesReference.MesaConsultasExternasCetipService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetCetip(idProposta, tipoPessoa);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasCetipService.Cetip> GetCetipAsync(string idProposta, ServicesReference.MesaConsultasExternasCetipService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetCetipAsync(idProposta, tipoPessoa);
        }
    }
}
