//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaConsultasExternasBureauPropriedadeService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BureauPropriedade", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Bureaus.Propriedade")]
    public partial class BureauPropriedade : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ServicesReference.MesaConsultasExternasBureauPropriedadeService.BureauImovel[] ImoveisField;
        
        private ServicesReference.MesaConsultasExternasBureauPropriedadeService.BureauVeiculo[] VeiculosField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasBureauPropriedadeService.BureauImovel[] Imoveis
        {
            get
            {
                return this.ImoveisField;
            }
            set
            {
                this.ImoveisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicesReference.MesaConsultasExternasBureauPropriedadeService.BureauVeiculo[] Veiculos
        {
            get
            {
                return this.VeiculosField;
            }
            set
            {
                this.VeiculosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BureauImovel", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Bureaus.Propriedade")]
    public partial class BureauImovel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CepField;
        
        private string EnderecoField;
        
        private string FonteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep
        {
            get
            {
                return this.CepField;
            }
            set
            {
                this.CepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco
        {
            get
            {
                return this.EnderecoField;
            }
            set
            {
                this.EnderecoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fonte
        {
            get
            {
                return this.FonteField;
            }
            set
            {
                this.FonteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BureauVeiculo", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Bureaus.Propriedade")]
    public partial class BureauVeiculo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AnoModeloField;
        
        private string FonteField;
        
        private string MarcaField;
        
        private string ModeloField;
        
        private string PlacaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnoModelo
        {
            get
            {
                return this.AnoModeloField;
            }
            set
            {
                this.AnoModeloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fonte
        {
            get
            {
                return this.FonteField;
            }
            set
            {
                this.FonteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca
        {
            get
            {
                return this.MarcaField;
            }
            set
            {
                this.MarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo
        {
            get
            {
                return this.ModeloField;
            }
            set
            {
                this.ModeloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa
        {
            get
            {
                return this.PlacaField;
            }
            set
            {
                this.PlacaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaConsultasExternasBureauPropriedadeService.IMesaConsultasExt" +
        "ernasBureauPropriedadeService")]
    public interface IMesaConsultasExternasBureauPropriedadeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasBureauPropriedadeService/GetBureauPropri" +
            "edade", ReplyAction="http://tempuri.org/IMesaConsultasExternasBureauPropriedadeService/GetBureauPropri" +
            "edadeResponse")]
        ServicesReference.MesaConsultasExternasBureauPropriedadeService.BureauPropriedade GetBureauPropriedade(string idProposta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasBureauPropriedadeService/GetBureauPropri" +
            "edade", ReplyAction="http://tempuri.org/IMesaConsultasExternasBureauPropriedadeService/GetBureauPropri" +
            "edadeResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasBureauPropriedadeService.BureauPropriedade> GetBureauPropriedadeAsync(string idProposta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaConsultasExternasBureauPropriedadeServiceChannel : ServicesReference.MesaConsultasExternasBureauPropriedadeService.IMesaConsultasExternasBureauPropriedadeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaConsultasExternasBureauPropriedadeServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaConsultasExternasBureauPropriedadeService.IMesaConsultasExternasBureauPropriedadeService>, ServicesReference.MesaConsultasExternasBureauPropriedadeService.IMesaConsultasExternasBureauPropriedadeService
    {
        
        public MesaConsultasExternasBureauPropriedadeServiceClient()
        {
        }
        
        public MesaConsultasExternasBureauPropriedadeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaConsultasExternasBureauPropriedadeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasBureauPropriedadeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasBureauPropriedadeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaConsultasExternasBureauPropriedadeService.BureauPropriedade GetBureauPropriedade(string idProposta)
        {
            return base.Channel.GetBureauPropriedade(idProposta);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasBureauPropriedadeService.BureauPropriedade> GetBureauPropriedadeAsync(string idProposta)
        {
            return base.Channel.GetBureauPropriedadeAsync(idProposta);
        }
    }
}
