//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaCreditoTokenService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MesaCreditoToken", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model")]
    public partial class MesaCreditoToken : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private System.DateTime DataGeracaoField;
        
        private string IdTokenField;
        
        private string UsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataGeracao
        {
            get
            {
                return this.DataGeracaoField;
            }
            set
            {
                this.DataGeracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdToken
        {
            get
            {
                return this.IdTokenField;
            }
            set
            {
                this.IdTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaCreditoTokenService.IMesaCreditoTokenService")]
    public interface IMesaCreditoTokenService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaCreditoTokenService/ObterUsuarioToken", ReplyAction="http://tempuri.org/IMesaCreditoTokenService/ObterUsuarioTokenResponse")]
        ServicesReference.MesaCreditoTokenService.MesaCreditoToken ObterUsuarioToken(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaCreditoTokenService/ObterUsuarioToken", ReplyAction="http://tempuri.org/IMesaCreditoTokenService/ObterUsuarioTokenResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaCreditoTokenService.MesaCreditoToken> ObterUsuarioTokenAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaCreditoTokenService/GerarToken", ReplyAction="http://tempuri.org/IMesaCreditoTokenService/GerarTokenResponse")]
        void GerarToken(string usuario, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaCreditoTokenService/GerarToken", ReplyAction="http://tempuri.org/IMesaCreditoTokenService/GerarTokenResponse")]
        System.Threading.Tasks.Task GerarTokenAsync(string usuario, string guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaCreditoTokenServiceChannel : ServicesReference.MesaCreditoTokenService.IMesaCreditoTokenService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaCreditoTokenServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaCreditoTokenService.IMesaCreditoTokenService>, ServicesReference.MesaCreditoTokenService.IMesaCreditoTokenService
    {
        
        public MesaCreditoTokenServiceClient()
        {
        }
        
        public MesaCreditoTokenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaCreditoTokenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaCreditoTokenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaCreditoTokenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaCreditoTokenService.MesaCreditoToken ObterUsuarioToken(string token)
        {
            return base.Channel.ObterUsuarioToken(token);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaCreditoTokenService.MesaCreditoToken> ObterUsuarioTokenAsync(string token)
        {
            return base.Channel.ObterUsuarioTokenAsync(token);
        }
        
        public void GerarToken(string usuario, string guid)
        {
            base.Channel.GerarToken(usuario, guid);
        }
        
        public System.Threading.Tasks.Task GerarTokenAsync(string usuario, string guid)
        {
            return base.Channel.GerarTokenAsync(usuario, guid);
        }
    }
}
