//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaConsultasExternasPortalService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPessoaEnum", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum TipoPessoaEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisaoGeral = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Proponente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avalista = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conjuge = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cnpj = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Portal", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Portal")]
    public partial class Portal : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool HistoricoDeAfastamentoField;
        
        private string InstituicaoField;
        
        private string NomeField;
        
        private decimal PrimeiraRemuneracaoBasicaBrutaField;
        
        private decimal SegundaRemuneracaoBasicaBrutaField;
        
        private decimal TerceiraRemuneracaoBasicaBrutaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HistoricoDeAfastamento
        {
            get
            {
                return this.HistoricoDeAfastamentoField;
            }
            set
            {
                this.HistoricoDeAfastamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instituicao
        {
            get
            {
                return this.InstituicaoField;
            }
            set
            {
                this.InstituicaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrimeiraRemuneracaoBasicaBruta
        {
            get
            {
                return this.PrimeiraRemuneracaoBasicaBrutaField;
            }
            set
            {
                this.PrimeiraRemuneracaoBasicaBrutaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SegundaRemuneracaoBasicaBruta
        {
            get
            {
                return this.SegundaRemuneracaoBasicaBrutaField;
            }
            set
            {
                this.SegundaRemuneracaoBasicaBrutaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TerceiraRemuneracaoBasicaBruta
        {
            get
            {
                return this.TerceiraRemuneracaoBasicaBrutaField;
            }
            set
            {
                this.TerceiraRemuneracaoBasicaBrutaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaConsultasExternasPortalService.IMesaConsultasExternasPortal" +
        "Service")]
    public interface IMesaConsultasExternasPortalService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasPortalService/GetPortal", ReplyAction="http://tempuri.org/IMesaConsultasExternasPortalService/GetPortalResponse")]
        ServicesReference.MesaConsultasExternasPortalService.Portal[] GetPortal(string idProposta, ServicesReference.MesaConsultasExternasPortalService.TipoPessoaEnum tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasPortalService/GetPortal", ReplyAction="http://tempuri.org/IMesaConsultasExternasPortalService/GetPortalResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasPortalService.Portal[]> GetPortalAsync(string idProposta, ServicesReference.MesaConsultasExternasPortalService.TipoPessoaEnum tipoPessoa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaConsultasExternasPortalServiceChannel : ServicesReference.MesaConsultasExternasPortalService.IMesaConsultasExternasPortalService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaConsultasExternasPortalServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaConsultasExternasPortalService.IMesaConsultasExternasPortalService>, ServicesReference.MesaConsultasExternasPortalService.IMesaConsultasExternasPortalService
    {
        
        public MesaConsultasExternasPortalServiceClient()
        {
        }
        
        public MesaConsultasExternasPortalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaConsultasExternasPortalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasPortalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasPortalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaConsultasExternasPortalService.Portal[] GetPortal(string idProposta, ServicesReference.MesaConsultasExternasPortalService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetPortal(idProposta, tipoPessoa);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasPortalService.Portal[]> GetPortalAsync(string idProposta, ServicesReference.MesaConsultasExternasPortalService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetPortalAsync(idProposta, tipoPessoa);
        }
    }
}
