//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesReference.MesaConsultasExternasSintegraService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPessoaEnum", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Enum")]
    public enum TipoPessoaEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisaoGeral = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Proponente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avalista = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conjuge = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cnpj = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sintegra", Namespace="http://schemas.datacontract.org/2004/07/SCDRetaguarda.Mesa.Interfaces.Model.Consu" +
        "ltasExternas.Sintegra")]
    public partial class Sintegra : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AtividadeEconomicaField;
        
        private string BairroField;
        
        private string CepField;
        
        private string CidadeField;
        
        private string EmpresaField;
        
        private string EnderecoCompletoField;
        
        private string LogradouroField;
        
        private string NumeroField;
        
        private string SituacaoCadastralField;
        
        private string TelefonesField;
        
        private string UfField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtividadeEconomica
        {
            get
            {
                return this.AtividadeEconomicaField;
            }
            set
            {
                this.AtividadeEconomicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro
        {
            get
            {
                return this.BairroField;
            }
            set
            {
                this.BairroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep
        {
            get
            {
                return this.CepField;
            }
            set
            {
                this.CepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade
        {
            get
            {
                return this.CidadeField;
            }
            set
            {
                this.CidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoCompleto
        {
            get
            {
                return this.EnderecoCompletoField;
            }
            set
            {
                this.EnderecoCompletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro
        {
            get
            {
                return this.LogradouroField;
            }
            set
            {
                this.LogradouroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SituacaoCadastral
        {
            get
            {
                return this.SituacaoCadastralField;
            }
            set
            {
                this.SituacaoCadastralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefones
        {
            get
            {
                return this.TelefonesField;
            }
            set
            {
                this.TelefonesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uf
        {
            get
            {
                return this.UfField;
            }
            set
            {
                this.UfField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReference.MesaConsultasExternasSintegraService.IMesaConsultasExternasSint" +
        "egraService")]
    public interface IMesaConsultasExternasSintegraService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasSintegraService/GetSintegra", ReplyAction="http://tempuri.org/IMesaConsultasExternasSintegraService/GetSintegraResponse")]
        ServicesReference.MesaConsultasExternasSintegraService.Sintegra[] GetSintegra(string idProposta, ServicesReference.MesaConsultasExternasSintegraService.TipoPessoaEnum tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaConsultasExternasSintegraService/GetSintegra", ReplyAction="http://tempuri.org/IMesaConsultasExternasSintegraService/GetSintegraResponse")]
        System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasSintegraService.Sintegra[]> GetSintegraAsync(string idProposta, ServicesReference.MesaConsultasExternasSintegraService.TipoPessoaEnum tipoPessoa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaConsultasExternasSintegraServiceChannel : ServicesReference.MesaConsultasExternasSintegraService.IMesaConsultasExternasSintegraService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaConsultasExternasSintegraServiceClient : System.ServiceModel.ClientBase<ServicesReference.MesaConsultasExternasSintegraService.IMesaConsultasExternasSintegraService>, ServicesReference.MesaConsultasExternasSintegraService.IMesaConsultasExternasSintegraService
    {
        
        public MesaConsultasExternasSintegraServiceClient()
        {
        }
        
        public MesaConsultasExternasSintegraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MesaConsultasExternasSintegraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasSintegraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MesaConsultasExternasSintegraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicesReference.MesaConsultasExternasSintegraService.Sintegra[] GetSintegra(string idProposta, ServicesReference.MesaConsultasExternasSintegraService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetSintegra(idProposta, tipoPessoa);
        }
        
        public System.Threading.Tasks.Task<ServicesReference.MesaConsultasExternasSintegraService.Sintegra[]> GetSintegraAsync(string idProposta, ServicesReference.MesaConsultasExternasSintegraService.TipoPessoaEnum tipoPessoa)
        {
            return base.Channel.GetSintegraAsync(idProposta, tipoPessoa);
        }
    }
}
